- app/Exceptions/Sentry.php
- tests/Unit/SentryTest.php
https://app.clickup.com/t/2fdyuu6
> refactor: ignore additional view exceptions

- tests/Unit/Console/Commands/ClearExpiredViewsTest.php
https://app.clickup.com/t/2aef22k
Ran the test > 3000 times and tried to find a logical reason for the test failing without luck. 
I suspect that may be related to the relative time used on the test so for now I just added a line to ensure the test runs always with a fixed date, that should prevent any random error
-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my UI changes in light AND dark mode
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] Documentation …
> fix: flaky cache clear test

- resources/views/components/navbar/logo.blade.php
https://app.clickup.com/t/2gbk9ck
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] Ready to be merged
> fix: navbar name spacing

- resources/views/components/navbar/logo.blade.php
https://app.clickup.com/t/2gbngb9
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] Ready to be merged
> fix: handle no navbar name

- .github/workflows/ci.yml
- app/DTO/Slot.php
- app/Http/Livewire/Concerns/DelegateData.php
- tests/Unit/DTO/SlotTest.php
https://app.clickup.com/t/2h7uedc
Doesn't specifically change the test, it caches more and slightly improves the speed of tests (DelegateDataBoxesTest suite went from around 10s to 6s locally)
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] Ready to be merged
> refactor: fix intermittent test

- .github/workflows/deps.yml
> chore: update deps workflow

- app/Models/Composers/ValueRangeComposer.php
- app/Services/Search/WalletSearch.php
- tests/Feature/Http/Livewire/SearchPageTest.php
https://app.clickup.com/t/2pm0xja
requires https://github.com/ArdentHQ/arkscan/pull/55
> fix: search wallet balance with username or vote name

- composer.json
- composer.lock
https://app.clickup.com/t/2ptfu0w
> refactor: handle all error codes

- app/Console/Commands/CacheCurrenciesHistory.php
https://app.clickup.com/t/2uhdw5u
> refactor: reduce currency history request frequency

- tests/Feature/Http/Livewire/DelegateDataBoxesTest.php
https://app.clickup.com/t/2pm17jj
> fix: intermittent next delegate test

- resources/views/components/latest-records-tabs.blade.php
Closes https://app.clickup.com/t/2vkwy7k
> fix: transactions filter mismatch when switching tabs

- package.json
- tsconfig.json
- yarn.lock
https://app.clickup.com/t/2uxanbq
> chore: remove TypeScript and Sass dependencies

- .github/workflows/deps.yml
- composer.json
- composer.lock
https://app.clickup.com/t/2v8tr9k
> chore: update js workflow

- tests/Unit/Services/MarketDataProviders/CoinGeckoTest.php
https://app.clickup.com/t/2z0h2j8
> fix: failing coingecko test by rounding value

- composer.lock
- config/web.php
- resources/lang/en/menus.php
- resources/lang/en/metatags.php
- resources/lang/en/pages.php
- resources/views/app/contact.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/ContactControllerTest.php
> refactor: contact form adjustments

- app/Http/Controllers/ContactController.php
- config/web.php
make subject more identifiable and human readable
> refactor: improve contact form subject for zendesk

- app/Http/Controllers/ContactController.php
> refactor: base zendesk tag on config value

- tests/Feature/Http/Livewire/Migration/TransactionsTest.php
- tests/Unit/Models/TransactionTest.php
https://app.clickup.com/t/862j05qtv
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged
> test: migration transaction list

- app/Http/Livewire/Migration/Stats.php
> fix: cast walletsMigrated cache to int

- app/Http/Livewire/WalletTable.php
https://app.clickup.com/t/86772m2rc
> refactor: ignore migration wallet in wallet list results

- app/Http/Livewire/Migration/Stats.php
- tests/Feature/Http/Livewire/Migration/StatsTest.php
https://app.clickup.com/t/86772mfh4
> fix: correctly calculate migration supply percentage

- resources/views/components/general/entity-header.blade.php
- resources/views/components/page-headers/wallet/frame-item.blade.php
https://app.clickup.com/t/862j0b2bb
> fix: light mode text color in dark headers

- resources/views/livewire/migration/wallet-highlight.blade.php
https://app.clickup.com/t/862j1azg1
> fix: wallet highlight scroll overflow

- config/explorer.php
- tests/TestCase.php
Part of https://app.clickup.com/t/8676xph1p
> fix: allow setting known wallets on devnet

- resources/views/components/details/migration-address.blade.php
- resources/views/components/grid/recipient.blade.php
https://app.clickup.com/t/862j1kbz2
> refactor: replace recipient avatar with migration icon in a transaction page

- resources/views/livewire/migration/stats.blade.php
- resources/views/livewire/migration/wallet-highlight.blade.php
- tests/Feature/Http/Controllers/MigrationControllerTest.php
https://app.clickup.com/t/862j1kj59
> refactor: remove decimals from the migrated amount

- resources/views/livewire/migration/wallet-highlight.blade.php
https://app.clickup.com/t/862j20qzw
> fix: migration wallets header overflow

- resources/views/components/general/identity.blade.php
- resources/views/components/tables/desktop/migration-transactions.blade.php
- resources/views/components/tables/rows/desktop/sender.blade.php
https://app.clickup.com/t/862j213wc
> refactor: migration transactions dynamic truncate address

- app/Jobs/BuildForgingStats.php
https://app.clickup.com/t/867747kkv
The culprit is the fact that these commands run in sync every minute. We don't have any overlap prevention atm and only sometimes (as can be seen in Sentry) we get race conditions where the job tries to UPSERT forging stats for some timestamp. One job will try to UPDATE, and when it can't find the record, it will try to INSERT. However, at that point, another job would already INSERT a record, resulting in an exception from the first job.
By wrapping this call in a database transaction, if we ever get an exception, we'll just retry the same UPSERT. At the next invocation, the chance of a new race condition is very low.
-   [ ] I checked my UI changes for any …
> fix: wrap forging stats upsert in a database transaction

- resources/views/components/general/identity.blade.php
- resources/views/components/tables/desktop/migration-transactions.blade.php
- resources/views/components/tables/rows/desktop/sender.blade.php
This removes the dynamic truncation as it didn't play well with the table
https://app.clickup.com/t/862j213wc
> fix: sender truncation on migration page

- app/Http/Controllers/MigrationController.php
- app/Services/Blockchain/Network.php
- resources/views/app/wallets.blade.php
- resources/views/components/navbar/navbar.blade.php
- tests/Feature/Http/Controllers/MigrationControllerTest.php
- tests/Unit/Services/Blockchain/NetworkTest.php
https://app.clickup.com/t/86774j5uk
> refactor: hide migration adjustments if no migration active

- .github/workflows/ci.yml
- .github/workflows/deps.yml
- .github/workflows/label.yml
- .github/workflows/ui.yml
- .svgo.js
Part of https://app.clickup.com/t/867748abv
> chore: update workflow deps

- resources/views/components/general/search/search-input.blade.php
https://app.clickup.com/t/86775ej17
> fix: search spinner odd spacing

- app/View/Components/TableSkeleton.php
- resources/views/components/skeleton.blade.php
- resources/views/components/tables/desktop/skeleton/migration-transactions.blade.php
- resources/views/components/tables/mobile/skeleton/migration-transactions.blade.php
- resources/views/components/tables/skeletons/desktop.blade.php
- resources/views/components/tables/skeletons/mobile.blade.php
https://app.clickup.com/t/867765285
> refactor: reduce migration transactions skeleton row count

- app/Services/Transactions/TransactionType.php
- app/ViewModels/Concerns/Transaction/DeterminesMigration.php
- app/ViewModels/Concerns/Transaction/HasType.php
- tests/Feature/Http/Livewire/WalletTransactionTableTest.php
- tests/Unit/Services/Transactions/TransactionTypeTest.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86777gjvr
> feat: migration additional tx checks

- app/Http/Livewire/Concerns/ManagesLatestTransactions.php
- app/Models/Transaction.php
- app/Services/Transactions/TransactionType.php
- app/Services/VendorField.php
- app/ViewModels/Concerns/Transaction/DeterminesMigration.php
- app/ViewModels/Concerns/Transaction/InteractsWithVendorField.php
- app/ViewModels/TransactionViewModel.php
- tests/Unit/Models/TransactionTest.php
- tests/Unit/Services/Transactions/TransactionTypeTest.php
- tests/Unit/Services/VendorFieldTest.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86777gjvr
> fix: migration transaction vendorfield checks

- app/Services/Blockchain/Network.php
- config/explorer.php
- resources/lang/en/urls.php
- resources/views/components/page-headers/migration.blade.php
https://app.clickup.com/t/86779mwhb
> refactor: allow migration URLs to be configured per network

- resources/views/app/compatible-wallets.blade.php
https://app.clickup.com/t/861mt7h2r
> fix: compatible wallets arkvault disclaimer text color

- resources/views/app/compatible-wallets.blade.php
- resources/views/components/compatible-wallets/arkvault.blade.php
- resources/views/components/compatible-wallets/header.blade.php
- resources/views/components/compatible-wallets/list-wallet.blade.php
- resources/views/components/compatible-wallets/section-divider.blade.php
- resources/views/components/compatible-wallets/wallet-grid.blade.php
Moves elements to separate components to avoid them all being part of a large file
> chore: restructure compatible-wallets components

- app/Http/Livewire/Navbar/Toggle.php
Fixes https://github.com/ArdentHQ/arkscan/actions/runs/4957581853/jobs/8869458085
> fix: ci toggle mobile value

- app/Providers/AppServiceProvider.php
- resources/lang/en/menus.php
- resources/views/components/navbar/navbar.blade.php
renames Wallets to Top Accounts in the navbar dropdown
> fix: rename wallets to top accounts in navbar

- resources/views/components/navbar/logo.blade.php
https://app.clickup.com/t/863gqxr3w
> refactor: increase navbar branding text size

- app/Providers/AppServiceProvider.php
- resources/lang/en/metatags.php
- resources/views/app/top-accounts.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
- tests/Feature/Http/Livewire/WalletTransactionTableTest.php
- tests/Unit/RedirectionTest.php
https://app.clickup.com/t/861mttd44
Wasn't sure whether to do temporary or permanent redirect. Left it as the default for now (302 - temporary), as that's what we used when we changed from the previous explorer to this one [here](https://github.com/ArdentHQ/arkscan/blob/develop/routes/web.php#L54-L56). …
> refactor: update routes

- phpunit.xml
- tests/Unit/Console/Commands/CacheCurrenciesDataTest.php
https://app.clickup.com/t/861mu5744
> fix: add network .env property to phpunit to avoid local test failures

- resources/views/components/general/dropdown/dropdown.blade.php
- resources/views/livewire/price-ticker.blade.php
Closes https://app.clickup.com/t/863guexty
> refactor: add scroll to price dropdown

- resources/views/components/navbar/navbar.blade.php
https://app.clickup.com/t/863gwjjy0
> fix: close navbar dropdown on outside click

- app/Http/Livewire/WalletTable.php
- resources/views/components/general/pagination/includes/middle.blade.php
Closes https://app.clickup.com/t/863gwjwzf
> fix: ensure page size is persisted in top wallets table

- app/Console/Commands/ScoutIndexModels.php
- config/horizon.php
As title says
1. ensure index jobs are not paused (you can just clear the cache `php artisan cache:clear`
2. run `php artisan scout:index-models`
3. on the app go to /horizon and ensure index jobs are running on scout queue
> feat: run scout jobs in his own queue

- routes/web.php
Adds a redirect from `/wallets` to `/top-accounts`. it also updates an old `/top-wallets` to point to the same page
> refactor: redirect wallets to top accounts

- routes/web.php
> chore: merge develop into staging

- app/Http/Livewire/TopAccountsTable.php
- tests/Feature/Http/Livewire/TopAccountsTableTest.php
https://app.clickup.com/t/862jzcvtd
> refactor: default 25 records per page on top accounts

- app/Providers/AppServiceProvider.php
https://app.clickup.com/t/861mxmdy5
> refactor: add statistics to navbar

- resources/views/components/general/identity.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/address.blade.php
- resources/views/components/tables/rows/mobile/encapsulated/address.blade.php
https://app.clickup.com/t/862jzkgch
> refactor: top accounts remove avatar

- app/Http/Livewire/WalletTables.php
This reduces the time to list transactions for a wallet by a lot, especially for older wallets. To notice the difference, open a wallet such as [AFxqVbsVuDfnfyd9ciRAuGq6waR5GqiC5R](https://live.arkscan.io/addresses/AFxqVbsVuDfnfyd9ciRAuGq6waR5GqiC5R) and compare that against the time it takes in this PR
-   [ ] Documentation _(if …
> perf: improve wallet details table transaction lookup

- resources/views/components/general/pagination/table.blade.php
https://app.clickup.com/t/862k0269r
> refactor: reduce show records font size

- resources/lang/en/general.php
- resources/views/components/tables/toolbars/transactions.blade.php
https://app.clickup.com/t/861myyz39
> refactor: disable transaction export button

- resources/views/components/tables/rows/desktop/encapsulated/address.blade.php
- resources/views/components/tables/rows/mobile/encapsulated/address.blade.php
https://app.clickup.com/t/862k0c0tf
> refactor: update top accounts copied tooltip text

- app/Http/Livewire/Concerns/HasTablePagination.php
- tests/Feature/Http/Livewire/TopAccountsTableTest.php
https://app.clickup.com/t/862k0dwr1
> refactor: go to page 1 on show records change

- resources/views/livewire/navbar/search.blade.php
https://app.clickup.com/t/861mz6g2n
> fix: avoid search icon briefly showing upon page refresh

- resources/views/components/wallet/overview/wallet.blade.php
- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
https://app.clickup.com/t/867863u4u
> fix: double up crypto value

- resources/views/components/navbar/network-dropdown.blade.php
- resources/views/livewire/price-ticker.blade.php
https://app.clickup.com/t/867863wda
Also fixes the mobile navbar dropdown(s)
> refactor: update navbar focus & colours

- resources/views/components/wallet/overview/delegate/productivity.blade.php
- resources/views/components/wallet/overview/wallet.blade.php
- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
https://app.clickup.com/t/867864yth
> refactor: hide wallet value if cannot be exchanged

- resources/views/components/modals/export-transactions/export-status.blade.php
https://app.clickup.com/t/863h53z96
> fix: wrong export warning image

- resources/views/components/modals/export-transactions/fields.blade.php
https://app.clickup.com/t/863h54112
> refactor: export reduce header row text size

- resources/views/components/input/js-select.blade.php
https://app.clickup.com/t/862k33c2m
> refactor: export dropdown placeholder dark mode color

- resources/views/components/general/dropdown/dropdown.blade.php
- resources/views/components/general/dropdown/filter.blade.php
- resources/views/components/navbar/network-dropdown.blade.php
- resources/views/livewire/price-ticker.blade.php
- resources/views/livewire/wallet-qr-code.blade.php
https://app.clickup.com/t/862k35u98
> fix: network dropdown button icon placement

- app/Http/Livewire/Concerns/HasTablePagination.php
- composer.json
- composer.lock
- resources/views/livewire/modals/export-transactions.blade.php
https://app.clickup.com/t/862k3539w
requires https://github.com/ArkEcosystem/laravel-foundation/pull/584
> refactor: export disable overlay close

- resources/views/components/input/js-select.blade.php
https://app.clickup.com/t/862k34hdw
> refactor: export dropdown show focus outline

- resources/views/components/tables/desktop/wallet-voters.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/value.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/vote-percentage.blade.php
https://app.clickup.com/t/861n17wgk
https://app.clickup.com/t/861n17wk3
> refactor: adjust value font styles on wallet page tables

- app/Http/Livewire/BlockTable.php
- app/Services/BigNumber.php
- tests/Feature/Http/Livewire/BlockTableTest.php
https://app.clickup.com/t/861n1awbm
> refactor: improve blocks overview pagination

- app/Http/Livewire/WalletBlockTable.php
- app/Http/Livewire/WalletTables.php
- app/Http/Livewire/WalletTransactionTable.php
- app/Http/Livewire/WalletVoterTable.php
- resources/views/components/loading/visible.blade.php
- resources/views/components/skeletons/wallet-blocks.blade.php
- resources/views/components/skeletons/wallet-transactions.blade.php
- resources/views/components/skeletons/wallet-voters.blade.php
- resources/views/livewire/wallet-block-table.blade.php
- resources/views/livewire/wallet-tables.blade.php
- resources/views/livewire/wallet-transaction-table.blade.php
- resources/views/livewire/wallet-voter-table.blade.php
- tests/Feature/Http/Livewire/WalletTablesTest.php
https://app.clickup.com/t/862k0u95d
> refactor: load wallet tab data on first activate

- resources/views/components/transaction/section-detail/transaction-type.blade.php
https://app.clickup.com/t/861n1fffe
> fix: tx type category color

- resources/views/components/transaction/section-detail/transaction-type.blade.php
https://app.clickup.com/t/861n1ffnw
> fix: delegate resignation username

- app/Services/NumberFormatter.php
- app/ViewModels/Concerns/Block/HasTransactions.php
- app/ViewModels/TransactionViewModel.php
- resources/lang/en/pages.php
- resources/views/app/transaction.blade.php
- resources/views/components/transaction/section-detail/summary-section.blade.php
- tests/Unit/Services/NumberFormatterTest.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/861n1ffh8
> feat: summary section

- app/Http/Livewire/Modals/ExportBlocks.php
- app/Http/Livewire/Modals/ExportTransactions.php
- app/ViewModels/Concerns/Wallet/CanBeDelegate.php
- resources/views/livewire/modals/export-blocks.blade.php
- resources/views/livewire/modals/export-transactions.blade.php
- tests/Feature/Http/Livewire/Modals/ExportBlocksTest.php
- tests/Feature/Http/Livewire/Modals/ExportTransactionsTest.php
https://app.clickup.com/t/861n21kk3
> refactor: defer export button loading

- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
- resources/views/components/tables/desktop/wallet-transactions.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/addressing.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/amount.blade.php
- resources/views/components/tables/rows/mobile/encapsulated/transaction.blade.php
- tests/Feature/Http/Livewire/WalletTransactionTableTest.php
https://app.clickup.com/t/861mz64ha
https://app.clickup.com/t/861n2tzuu
> refactor: update transfer sent to self design

- app/Http/Livewire/WalletTransactionTable.php
- resources/views/components/skeletons/wallet-blocks.blade.php
- resources/views/components/skeletons/wallet-transactions.blade.php
- resources/views/components/skeletons/wallet-voters.blade.php
- resources/views/components/tables/desktop/wallet-blocks.blade.php
- resources/views/components/tables/desktop/wallet-transactions.blade.php
- resources/views/components/tables/mobile/transactions.blade.php
- resources/views/components/tables/mobile/wallet-transactions.blade.php
- resources/views/livewire/wallet-transaction-table.blade.php
https://app.clickup.com/t/862k5n94b
> fix: table age value on wallet page

- app/Services/ExchangeRate.php
- app/ViewModels/TransactionViewModel.php
- resources/views/components/transaction/section-detail/row.blade.php
- resources/views/components/transaction/section-detail/summary-section.blade.php
- tests/Unit/Services/ExchangeRateTest.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/863h8kmdx
> refactor: show small values in transaction summary

- resources/views/components/transaction/section-detail/summary-section.blade.php
https://app.clickup.com/t/862k615jw
> refactor: don't show cryptocurrency small values

- app/Http/Controllers/ShowBlockController.php
- app/Http/Livewire/BlockTransactionsTable.php
- app/Http/Livewire/Concerns/HasLazyLoadingPagination.php
- app/ViewModels/Concerns/Block/HasTransactions.php
- resources/views/components/block/page/transaction-list.blade.php
- resources/views/components/general/pagination/lazy-loading.blade.php
- resources/views/components/tables/desktop/block-transactions.blade.php
- resources/views/components/tables/mobile/block-transactions.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/addressing-generic.blade.php
- resources/views/livewire/block-transactions-table.blade.php
- tests/Feature/Http/Livewire/BlockTransactionsTableTest.php
https://app.clickup.com/t/862k68g3x
todo: 
> refactor: block transactions lazy loading

- resources/views/components/block/page/details.blade.php
- resources/views/components/block/page/section-detail/row.blade.php
- resources/views/components/general/page-section/row.blade.php
- resources/views/components/transaction/page/section-detail/row.blade.php
https://app.clickup.com/t/861n1fg2t
> fix: zero transaction count

- app/Http/Livewire/BlockTransactionsTable.php
- resources/views/components/general/pagination/lazy-loading.blade.php
- resources/views/livewire/block-transactions-table.blade.php
- tests/Feature/Http/Livewire/BlockTransactionsTableTest.php
https://app.clickup.com/t/862k68g3x
> refactor: don't defer lazy loaded block transaction table

- composer.json
- composer.lock
https://app.clickup.com/t/862k7fejz
> chore: update foundation dependency

- app/Contracts/Services/Monitor/MissedBlocksCalculator.php
- app/Facades/Services/Monitor/MissedBlocksCalculator.php
- app/Jobs/BuildForgingStats.php
- app/Models/ForgingStats.php
- app/Providers/AppServiceProvider.php
- app/Services/Monitor/MissedBlocksCalculator.php
- database/migrations/2023_08_07_183334_add_missed_height_to_forging_stats_table.php
- tests/Unit/Console/Commands/BuildForgingStatsTest.php
- tests/migrations/2023_08_07_183334_add_missed_height_to_forging_stats_table.php
https://app.clickup.com/t/861n4ynf9
> refactor: forging stats missed block height

- resources/views/components/tables/desktop/delegates/list-table.blade.php
- resources/views/components/tables/desktop/delegates/missed-blocks.blade.php
> refactor: change info icon in delegate tables

- resources/views/components/tables/mobile/delegates/list-table.blade.php
- resources/views/components/tables/mobile/delegates/missed-blocks.blade.php
- resources/views/components/tables/mobile/delegates/recent-votes.blade.php
https://app.clickup.com/t/861n6thnx
> fix: mobile row is expanded console error

- app/Jobs/BuildForgingStats.php
- tests/Unit/Console/Commands/BuildForgingStatsTest.php
https://app.clickup.com/t/861n6u0j7
> fix: forging stats memory usage

- resources/lang/en/pages.php
- resources/lang/en/pagination.php
- resources/views/components/tables/toolbars/delegates/missed-blocks.blade.php
- resources/views/components/tables/toolbars/delegates/recent-votes.blade.php
- resources/views/components/tables/toolbars/toolbar.blade.php
https://app.clickup.com/t/861n6uk44
> refactor: 30 days table toolbar suffix

- resources/views/components/general/network-currency.blade.php
- resources/views/components/wallet/overview/delegate.blade.php
- resources/views/components/wallet/overview/delegate/votes.blade.php
- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
https://app.clickup.com/t/862k98yea
> fix: delegate votes & forged truncation in wallet overview

- resources/views/components/tables/desktop/wallet-voters.blade.php
- resources/views/components/tables/headers/mobile/encapsulated/address.blade.php
- resources/views/components/tables/mobile/wallet-voters.blade.php
https://app.clickup.com/t/861n9936k
> refactor: delegate voters show username if available

- resources/views/components/tables/rows/desktop/encapsulated/addressing-generic.blade.php
- tests/Feature/Http/Livewire/TransactionTableTest.php
https://app.clickup.com/t/861n9jrf0
> fix: slow transactions page

- app/Http/Controllers/BlocksController.php
- app/Models/ForgingStats.php
- resources/lang/en/pages.php
- resources/views/app/blocks.blade.php
- resources/views/components/page-headers/blocks.blade.php
- resources/views/components/page-headers/blocks/block-rewards.blade.php
- resources/views/components/page-headers/blocks/blocks-produced.blade.php
- resources/views/components/page-headers/blocks/largest-block.blade.php
- resources/views/components/page-headers/blocks/missed-blocks.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/BlocksControllerTest.php
https://app.clickup.com/t/861n8pr6e
> feat: blocks page stats

- resources/views/components/tables/filters/transactions-generic.blade.php
https://app.clickup.com/t/861n8pvyf
> refactor: transactions filter icon remove text

- resources/views/livewire/delegates/tabs.blade.php
- resources/views/livewire/wallet-tables.blade.php
https://app.clickup.com/t/862kbrrb3
> fix: hide mobile dropdown options until page load

- resources/views/components/tables/mobile/blocks.blade.php
https://app.clickup.com/t/861n8ptbb
> refactor: update blocks table spacing on sm devices

- resources/views/components/tables/desktop/delegates/list-table.blade.php
- resources/views/components/tables/desktop/delegates/missed-blocks.blade.php
https://app.clickup.com/t/862kbwzyh
> refactor: update tooltip icon on delegate tables

- app/Http/Controllers/TransactionsController.php
- tests/Feature/Http/Controllers/TransactionsControllerTest.php
https://app.clickup.com/t/862kbytg1
> fix: transaction volume include multipayments

- resources/views/components/tables/desktop/blocks.blade.php
- resources/views/components/tables/desktop/skeleton/blocks.blade.php
- resources/views/components/tables/desktop/skeleton/wallet-blocks.blade.php
- resources/views/components/tables/desktop/wallet-blocks.blade.php
- resources/views/components/tables/mobile/skeleton/wallet-blocks.blade.php
- resources/views/components/tables/mobile/wallet-blocks.blade.php
https://app.clickup.com/t/862kby0gd
> refactor: wallet blocks hide value when not exchangeable & update breakpoints

- resources/views/components/tables/rows/desktop/encapsulated/delegates/delegate-status.blade.php
https://app.clickup.com/t/861narw07
> fix: delegate table status badge hover styling

- resources/lang/en/metatags.php
- resources/views/components/metadata.blade.php
To avoid cached images for previews, use `laravel mix` as that adds a hash to the filename
> refactor: use laravel mix for meta images

- resources/views/components/tables/desktop/transaction-participants.blade.php
https://app.clickup.com/t/862kdfgan
Caused by a single-column table, it didn't like being the first and last column. Fixed by adding an empty column, as it didn't seem worth putting too much time into adjusting the CSS which could have caused additional issues elsewhere
- …
> refactor: fix participants hover issue

- resources/views/components/tables/desktop/skeleton/delegates/list-table.blade.php
- resources/views/components/tables/desktop/skeleton/delegates/missed-blocks.blade.php
- resources/views/components/tables/desktop/skeleton/delegates/recent-votes.blade.php
- resources/views/components/tables/headers/desktop/address.blade.php
- resources/views/components/tables/headers/desktop/includes/livewire-sort-icon.blade.php
- resources/views/components/tables/headers/desktop/number.blade.php
- resources/views/components/tables/headers/desktop/sortable-header.blade.php
- resources/views/components/tables/headers/desktop/text.blade.php
- resources/views/components/tables/skeletons/encapsulated/desktop.blade.php
https://app.clickup.com/t/862kdu11n
> refactor: add sort icon to skeleton

- app/Http/Livewire/Delegates/Delegates.php
- tests/Feature/Http/Livewire/Delegates/DelegatesTest.php
https://app.clickup.com/t/862kdwfh7
> refactor: delegates sort by missed blocks

- resources/lang/en/general.php
- resources/views/components/tables/rows/desktop/encapsulated/voting.blade.php
https://app.clickup.com/t/862kev1q9
> refactor: top accounts voting tooltip

- resources/views/components/tables/desktop/home/transactions.blade.php
https://app.clickup.com/t/861n1tte6
> refactor: home transactions responsive fee

- app/Http/Livewire/Home/Chart.php
https://app.clickup.com/t/862kf47cg
> fix: use initial dataset value to determine chart color

- resources/views/components/tables/mobile/wallet-transactions.blade.php
https://app.clickup.com/t/862kez0np
> fix: wallet transactions mobile amount badge styling

- resources/views/components/home/header.blade.php
- resources/views/livewire/home/chart.blade.php
https://app.clickup.com/t/862kf2haf
> fix: home mobile chart hidden

- resources/views/components/tables/desktop/home/blocks.blade.php
- resources/views/components/tables/desktop/skeleton/home/blocks.blade.php
https://app.clickup.com/t/862kdx4pw
Also adds missing Generated By column for loading state
> refactor: home blocks loading state tooltips

- app/Providers/AppServiceProvider.php
- resources/lang/en/urls.php
https://app.clickup.com/t/862kamdxn
> fix: documentation links

- app/Providers/AppServiceProvider.php
- resources/lang/en/menus.php
- resources/lang/en/urls.php
https://app.clickup.com/t/862kfen4w
> chore: add github link to navbar

- composer.lock
- config/social.php
https://app.clickup.com/t/862kfjmuf
requires https://github.com/ArkEcosystem/laravel-foundation/pull/601
> chore: change twitter to x

- app/Http/Livewire/Delegates/MissedBlocks.php
- resources/views/components/tables/desktop/delegates/missed-blocks.blade.php
- resources/views/components/tables/desktop/skeleton/delegates/missed-blocks.blade.php
- tests/Feature/Http/Livewire/Delegates/MissedBlocksTest.php
https://app.clickup.com/t/862kdkh56
> refactor: sqlite disable missed block sorting

- resources/views/components/navbar/mobile.blade.php
- resources/views/components/navbar/navbar.blade.php
https://app.clickup.com/t/862kfrxg8
> refactor: change navbar anchor for page autoscroll

- resources/views/components/search/results/block.blade.php
- resources/views/components/search/results/transaction-types/multi-payment.blade.php
- resources/views/components/search/results/transaction-types/other.blade.php
- resources/views/components/search/results/transaction-types/transfer.blade.php
- resources/views/components/search/results/transaction-types/vote.blade.php
- resources/views/components/search/results/transaction.blade.php
- resources/views/components/search/results/wallet.blade.php
https://app.clickup.com/t/862kgbnv6
> fix: search results dark mode styling

- resources/views/components/navbar/desktop.blade.php
- resources/views/components/navbar/item.blade.php
- resources/views/components/navbar/list-item.blade.php
- resources/views/components/navbar/mobile.blade.php
https://app.clickup.com/t/862kgbwg2
> fix: navbar menu dropdowns styling in dark mode

- resources/views/components/stats/stat.blade.php
https://app.clickup.com/t/862kgcu78
> refactor: statistics padding on info boxes

- app/Http/Livewire/Delegates/HeaderStats.php
- resources/views/components/page-headers/delegates.blade.php
- resources/views/components/page-headers/delegates/voting.blade.php
- resources/views/livewire/delegates/header-stats.blade.php
- tests/Feature/Http/Livewire/Delegates/HeaderStatsTest.php
https://app.clickup.com/t/862kgcu81
> refactor: delegate stats voting percentage

- app/Http/Livewire/Stats/Chart.php
https://app.clickup.com/t/862kgcu7q
> fix: statistics use user currency for min & max price

- app/Http/Livewire/StatsHighlights.php
- resources/views/livewire/stats-highlights.blade.php
- tests/Feature/Http/Livewire/StatsHighlightsTest.php
https://app.clickup.com/t/862kgcxf0
> refactor: statistics consistent voting count

- app/Http/Livewire/Stats/Chart.php
https://app.clickup.com/t/862kg5cy1
> fix: statistics chart always red

- resources/views/components/tables/rows/mobile/skeletons/encapsulated/address.blade.php
- resources/views/components/tables/skeletons/encapsulated/mobile/top-accounts.blade.php
https://app.clickup.com/t/862kgczx6
> fix: top accounts mobile address loading state

- resources/views/components/stats/insight.blade.php
https://app.clickup.com/t/862kgg89f
> refactor: statistics semi bold header values

- app/Console/Commands/CacheDelegateVoterCounts.php
- app/Services/Cache/DelegateCache.php
- tests/Feature/Http/Livewire/Delegates/HeaderStatsTest.php
- tests/Feature/Http/Livewire/StatsHighlightsTest.php
- tests/Unit/Console/Commands/CacheDelegateVoterCountsTest.php
https://app.clickup.com/t/862kgdngv
> refactor: total voter count calculation command

- resources/views/components/tables/headers/desktop/sortable-header.blade.php
https://app.clickup.com/t/862kg5ca4
> fix: sortable header duplicate classes from merge

- resources/views/livewire/stats/chart.blade.php
https://app.clickup.com/t/862kgg89f
> refactor: statistics semibold chart price

- resources/views/components/stats/insight.blade.php
- resources/views/livewire/stats/chart.blade.php
https://app.clickup.com/t/862khqwng and https://app.clickup.com/t/862khqwv7
> refactor: update statistics card padding

- resources/views/components/tables/desktop/delegates/monitor.blade.php
- resources/views/components/tables/mobile/delegates/monitor.blade.php
- resources/views/livewire/delegates/monitor.blade.php
https://app.clickup.com/t/862khvkt2
> fix: delegate monitor round change responsive

- app/Console/Commands/CacheDevelopmentData.php
- app/Console/Commands/CacheVolume.php
- app/Console/Kernel.php
- app/Contracts/MarketDataProvider.php
- app/Http/Livewire/Home/Statistics.php
- app/Services/Cache/CryptoDataCache.php
- app/Services/MarketCap.php
- app/Services/MarketDataProviders/CoinGecko.php
- app/Services/MarketDataProviders/CryptoCompare.php
- app/Services/NumberFormatter.php
- resources/views/livewire/home/statistics.blade.php
- tests/Feature/Http/Livewire/Home/StatisticsTest.php
- tests/Unit/Console/Commands/CacheVolumeTest.php
- tests/Unit/Services/MarketDataProviders/CoinGeckoTest.php
- tests/Unit/Services/MarketDataProviders/CryptoCompareTest.php
- tests/Unit/Services/NumberFormatterTest.php
https://app.clickup.com/t/862khv2rk
TODO:
> feat: show exchange volume on homepage statistics

- resources/lang/en/pages.php
- resources/views/livewire/home/statistics.blade.php
https://app.clickup.com/t/862khzazw
> fix: adjust volume labels for ambiguity

- app/Services/Cache/DelegateCache.php
- tests/Unit/Services/Cache/DelegateCacheTest.php
https://app.clickup.com/t/86dqkruh2
> fix: voter cache return types

- resources/lang/en/pages.php
- resources/views/livewire/stats-highlights.blade.php
- tests/Feature/Http/Livewire/StatsHighlightsTest.php
https://app.clickup.com/t/86dqn9g4h
> refactor: statistics update texts

- app/Console/Commands/CacheTransactions.php
- app/Http/Livewire/Stats/Insights.php
- app/Services/Cache/TransactionCache.php
- app/Services/Timestamp.php
- app/Services/Transactions/Aggregates/Historical/AveragesAggregate.php
- app/Services/Transactions/Aggregates/HistoricalAggregateFactory.php
- resources/lang/en/pages.php
- resources/views/components/stats/insights/transactions.blade.php
- resources/views/livewire/stats/insights.blade.php
- tests/Feature/Http/Livewire/Stats/InsightsTest.php
- tests/Feature/Http/Livewire/__stubs/NetworkStub.php
- tests/Unit/Services/Transactions/Aggregates/Historical/AveragesAggregateTest.php
https://app.clickup.com/t/86dqn9gdt
> feat: statistics transaction daily averages

- app/Console/Commands/CacheAddressStatistics.php
- app/Console/Kernel.php
- app/Http/Livewire/Stats/Insights.php
- app/Services/Addresses/Aggregates/HoldingsAggregate.php
- app/Services/Cache/Statistics.php
- resources/lang/en/pages.php
- resources/views/components/stats/insights/addresses.blade.php
- resources/views/livewire/stats/insights.blade.php
- tests/Feature/Http/Livewire/Stats/InsightsTest.php
- tests/Unit/Console/Commands/CacheAddressStatisticsTest.php
https://app.clickup.com/t/86dqn9j3k
TODO:
> feat: address holdings statistics

- resources/views/components/stats/insights/marketdata.blade.php
https://app.clickup.com/t/86dqumt2t
https://app.clickup.com/t/86dqumrfm
> fix: market data ranges styling on mobile

- app/Console/Commands/CacheAddressStatistics.php
- app/Services/Cache/StatisticsCache.php
https://app.clickup.com/t/86dqtd90x
> feat: newest wallet statistics

- resources/views/components/stats/insights/container.blade.php
- resources/views/components/stats/insights/transactions.blade.php
https://app.clickup.com/t/86dqut8g3
> fix: stats container spacing mobile interference

- app/Console/Commands/CacheMarketDataStatistics.php
- app/Contracts/MarketDataProvider.php
- app/Http/Livewire/Stats/Insights.php
- app/Services/Cache/CryptoDataCache.php
- app/Services/Cache/StatisticsCache.php
- app/Services/MarketDataProviders/CoinGecko.php
- app/Services/MarketDataProviders/CryptoCompare.php
- resources/views/components/stats/insights/marketdata.blade.php
- tests/Feature/Http/Livewire/Stats/InsightsTest.php
- tests/Unit/Console/Commands/CacheMarketDataStatisticsTest.php
- tests/Unit/Services/MarketDataProviders/CoinGeckoTest.php
- tests/Unit/Services/MarketDataProviders/CryptoCompareTest.php
> Revert "feat: support multiple currencies for marketdata"

- resources/views/components/stats/insights/desktop/transaction-record-row.blade.php
- resources/views/components/stats/insights/mobile/transaction-record-row.blade.php
follow up for https://app.clickup.com/t/86dqvp85h
> fix: force 0 decimals for transaction record amounts

- resources/views/components/stats/insights/desktop/transaction-record-row.blade.php
- resources/views/components/stats/insights/mobile/transaction-record-row.blade.php
another follow up to https://app.clickup.com/t/86dqvp85h
> fix: handle decimals ending in 0 in insights

- composer.lock
- resources/views/components/stats/insights/desktop/transaction-record-row.blade.php
- resources/views/components/stats/insights/mobile/transaction-record-row.blade.php
- tests/Unit/Services/NumberFormatterTest.php
https://app.clickup.com/t/86dqvpe9q
> fix: numberformatter 0 decimals edge case

- composer.json
- composer.lock
- resources/views/components/general/network-currency.blade.php
- tests/Unit/Services/NumberFormatterTest.php
This temporary downgrades the foundation version to get the old number formatting back (with its issues) as it requires additional handling in this codebase to work with the proper formatting
> fix: wallet amount value

- app/Services/NumberFormatter.php
- composer.json
- composer.lock
- resources/views/components/general/network-currency.blade.php
- resources/views/components/page-headers/delegates/voting.blade.php
- resources/views/components/search/results/transaction.blade.php
- resources/views/components/search/results/wallet.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/balance.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/delegates/votes.blade.php
- tests/Unit/Services/NumberFormatterTest.php
https://app.clickup.com/t/86dqvq80m
> refactor: currency formatting

- resources/views/app/home.blade.php
- resources/views/components/home/footer.blade.php
https://app.clickup.com/t/86dqq37hj
> refactor: home mobile divider

- resources/views/components/general/dropdown/filter.blade.php
- resources/views/livewire/modals/export-blocks.blade.php
- resources/views/livewire/modals/export-transactions.blade.php
https://app.clickup.com/t/86dqq37uv
> refactor: mobile export filter button size

- resources/views/layouts/app.blade.php
https://app.clickup.com/t/86dqq38g0
> refactor: mobile footer padding

- resources/views/components/tables/rows/mobile/encapsulated/amount.blade.php
https://app.clickup.com/t/86dqq38dw
> fix: mobile full width transaction amount

- resources/views/components/tables/mobile/block-transactions.blade.php
- resources/views/components/tables/mobile/top-accounts.blade.php
- resources/views/components/tables/mobile/transaction-participants.blade.php
- resources/views/components/tables/mobile/transaction-recipients.blade.php
- resources/views/components/tables/mobile/wallet-blocks.blade.php
- resources/views/components/tables/mobile/wallet-transactions.blade.php
- resources/views/components/tables/mobile/wallet-voters.blade.php
https://app.clickup.com/t/86dqq281u
> refactor: mobile row wire keys

- resources/views/livewire/modals/export-blocks.blade.php
- resources/views/livewire/modals/export-transactions.blade.php
- resources/views/livewire/modals/submit-exchange.blade.php
- resources/views/livewire/modals/submit-wallet.blade.php
https://app.clickup.com/t/86dr41w6h
> refactor: modal close button background

- docker/Dockerfile
Fix Dockerfile
-   [X] Ready to be merged
> fix: dockerfile incorrect command

- resources/views/components/general/dropdown/alpine-list-item.blade.php
- resources/views/components/navbar/theme-dropdown.blade.php
https://app.clickup.com/t/86dr4kzbh
https://app.clickup.com/t/86dr42vzx
> refactor: theme dropdown colors

- app/Http/Livewire/WalletQrCode.php
- tests/Feature/Http/Livewire/WalletQrCodeTest.php
https://app.clickup.com/t/86dr41x4a
> fix: qr code negative amount error

- resources/views/livewire/wallet-qr-code.blade.php
https://app.clickup.com/t/86dr4r006
> refactor: dim & dark qr code color updates

- app/Console/Commands/CacheAnnualStatistics.php
- app/Console/Commands/CacheDelegatePerformance.php
- app/Console/Commands/CacheDelegateUsernames.php
- app/Console/Kernel.php
- app/Contracts/RoundRepository.php
- app/Facades/Rounds.php
- app/Http/Controllers/BlocksController.php
- app/Http/Livewire/Concerns/DelegateData.php
- app/Http/Livewire/DelegateDataBoxes.php
- app/Http/Livewire/Delegates/RecentVotes.php
- app/Jobs/BuildForgingStats.php
- app/Models/Casts/UnixSeconds.php
- app/Models/Round.php
- app/Models/State.php
- app/Models/Transaction.php
- app/Models/Wallet.php
- app/Repositories/RoundRepository.php
- app/Services/Blockchain/Network.php
- app/Services/Blocks/Aggregates/LargestBlockAggregate.php
- app/Services/Monitor/MissedBlocksCalculator.php
- app/Services/Monitor/Monitor.php
- app/Services/Transactions/Aggregates/Historical/AveragesAggregate.php
- app/Services/Transactions/TransactionType.php
- app/ViewModels/Concerns/Transaction/InteractsWithVotes.php
- database/factories/TransactionFactory.php
> refactor(mainsail): update delegate wallets more frequently

- app/Console/Commands/CacheDelegateUsernames.php
- app/Console/Commands/CacheDelegateVoterCounts.php
- app/Console/Commands/CacheDelegateWallets.php
- app/Contracts/WalletRepository.php
- app/Facades/Wallets.php
- app/Repositories/WalletRepository.php
- app/Repositories/WalletRepositoryWithCache.php
- app/Services/Monitor/Aggregates/DelegateTotalAggregates.php
> fix(mainsail): use `allWithValidatorPublicKey` to get validator wallets

- app/Console/Commands/CacheDelegatePerformance.php
- app/Console/Commands/CacheDelegateUsernames.php
- app/Http/Livewire/DelegateDataBoxes.php
- app/ViewModels/Concerns/Wallet/CanForge.php
- resources/views/livewire/delegates/monitor.blade.php
> fix(mainsail): further monitor improvements

- app/ViewModels/Concerns/Wallet/CanForge.php
- resources/lang/en/general.php
- resources/lang/en/pages.php
- resources/views/components/delegates/missed-warning.blade.php
- resources/views/components/tables/desktop/delegates/monitor.blade.php
- resources/views/components/tables/mobile/delegates/monitor.blade.php
- tests/Feature/Http/Livewire/Delegates/MonitorTest.php
- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86dt0dttd
Struggled to test as the monitor kept 504-ing locally.
Todo:
> refactor: monitor delegate missing icon

- .github/workflows/ci.yml
Temporarily disable phpstan workflow for mainsail development - until we get around to fixing those
> chore: temporarily disable failing workflows

- .github/workflows/ci.yml
- app/Console/Commands/CacheUsernames.php
- app/Models/Round.php
- app/Models/Transaction.php
- app/Services/Transactions/TransactionType.php
- app/ViewModels/Concerns/Wallet/CanHaveUsername.php
- app/ViewModels/TransactionViewModel.php
https://app.clickup.com/t/86dt3ttm7
> fix: phpstan

- .github/workflows/ci.yml
- composer.json
- phpunit.xml
https://app.clickup.com/t/86dt2zvg6
> chore: enable tests workflow

- app/Console/Commands/CacheAnnualStatistics.php
- app/Console/Commands/CacheValidatorStatistics.php
- app/Jobs/BuildForgingStats.php
- app/Models/ForgingStats.php
- composer.json
- database/factories/TransactionFactory.php
- database/migrations/2024_04_03_121300_change_forging_stats_timestamp_column_type.php
- phpunit.xml
- tests/Helpers.php
- tests/Unit/Console/Commands/BuildForgingStatsTest.php
- tests/Unit/Console/Commands/CacheAnnualStatisticsTest.php
- tests/Unit/Console/Commands/CacheBlocksTest.php
- tests/Unit/Console/Commands/CachePricesTest.php
- tests/Unit/Console/Commands/CacheValidatorPerformanceTest.php
- tests/Unit/Console/Commands/CacheValidatorProductivityTest.php
- tests/Unit/Console/Commands/CacheValidatorStatisticsTest.php
- tests/Unit/Console/Commands/CacheValidatorVoterCountsTest.php
- tests/Unit/Console/Commands/CacheValidatorWalletsTest.php
- tests/Unit/Console/Commands/CacheValidatorsWithVotersTest.php
- tests/Unit/Console/Commands/CacheVolumeTest.php
- tests/migrations/2024_04_03_121300_change_forging_stats_timestamp_column_type.php
https://app.clickup.com/t/86dt3u59j
I removed a few tests from `CacheValidatorPerformanceTest` as I found it a little unclear what it was testing
> fix: command tests

- app/Models/ForgingStats.php
Related to [app.clickup.com/t/86dt3u59j](https://app.clickup.com/t/86dt3u59j)
> refactor: remove forging stats connection

- app/DTO/Payment.php
- phpunit.xml
- tests/Unit/DTO/MemoryWalletTest.php
- tests/Unit/DTO/PaymentTest.php
- tests/Unit/DTO/SlotTest.php
https://app.clickup.com/t/86dt3u5ah
> fix: DTO tests

- app/Console/Commands/CacheAddressStatistics.php
- tests/Unit/Console/Commands/CacheAddressStatisticsTest.php
https://app.clickup.com/t/86dt5q334
Also fixed a test relating to this, but it won't be run/covered just yet due to how the tests are being refactored
> fix: statistics newest address date format

- tests/Unit/Models/RoundTest.php
- tests/Unit/Models/TransactionTest.php
- tests/Unit/Models/WalletTest.php
https://app.clickup.com/t/86dt3u5cd
> fix: model tests

- app/Console/Kernel.php
https://app.clickup.com/t/86dt2jxyx
> refactor: only run fetch exchanges job on production

- phpunit.xml
- tests/Unit/Repositories/RoundRepositoryWithCacheTest.php
- tests/Unit/Repositories/TransactionRepositoryTest.php
- tests/Unit/Repositories/TransactionRepositoryWithCacheTest.php
- tests/Unit/Repositories/WalletRepositoryTest.php
- tests/Unit/Repositories/WalletRepositoryWithCacheTest.php
https://app.clickup.com/t/86dt3u5cy
> fix: repository tests

- phpunit.xml
- tests/Unit/Jobs/IndexBlocksTest.php
- tests/Unit/Jobs/IndexTransactionsTest.php
https://app.clickup.com/t/86dt3u5be
> fix: job tests

- composer.json
- phpunit.xml
- tests/Unit/DTO/SlotTest.php
https://app.clickup.com/t/86dt3u5fw
> refactor: enable all unit tests  update coverage

- phpunit.xml
- tests/Feature/Http/Livewire/Concerns/HasTablePaginationTest.php
- tests/Feature/Http/Livewire/Validators/MonitorTest.php
- tests/Feature/Http/Livewire/__stubs/HasTablePaginationStub.php
https://app.clickup.com/t/86dt3u5g7
> fix: analysis tests

- app/Services/VendorField.php
- tests/Unit/Services/VendorFieldTest.php
https://app.clickup.com/t/86dt8x6cw
> refactor: remove vendorfield hex conversion

- app/Http/Livewire/Concerns/DelegateData.php
- app/Repositories/RoundRepositoryWithCache.php
- tests/Unit/Repositories/RoundRepositoryWithCacheTest.php
https://app.clickup.com/t/86dt8a2gv
> refactor: improve performance

- resources/lang/en/pages.php
- resources/lang/en/urls.php
- resources/views/components/compatible-wallets/arkconnect.blade.php
- resources/views/components/general/learn-more.blade.php
https://app.clickup.com/t/86dt9qf9c
> fix: arkconnect learn more url

- tests/Feature/Http/Livewire/DelegateDataBoxesTest.php
- tests/Helpers.php
- tests/Stubs/FullPartialRoundException.php
https://app.clickup.com/t/86dt1vmv9
> test: fix intermittently failing tests

- app/Console/Commands/CacheAddressStatistics.php
- tests/Unit/Console/Commands/CacheAddressStatisticsTest.php
https://app.clickup.com/t/86dtacrfv
> refactor: update last updated height cache key

- resources/views/components/general/dropdown/list-item.blade.php
https://app.clickup.com/t/86dt0wcuy
> refactor: prevent network dropdown redirect on same site

- resources/views/components/general/page-section/container.blade.php
- resources/views/components/transaction/page/memo.blade.php
https://app.clickup.com/t/86dtayknq
> refactor: memo break words

- resources/css/_general.css
- resources/views/components/compatible-wallets/arkconnect.blade.php
- resources/views/components/compatible-wallets/learn-more.blade.php
- resources/views/components/general/learn-more.blade.php
https://app.clickup.com/t/86dtd7xxm
> fix: wallet learn more arrows

- resources/views/components/tables/desktop/delegates/list-table.blade.php
https://app.clickup.com/t/86dtdybp0
> refactor: prevent extension logic when disabled

- resources/views/components/delegates/vote-link.blade.php
https://app.clickup.com/t/86dt0dttt
> refactor: update vote popup header color on dark & dim

- resources/lang/en/general.php
- resources/views/livewire/wallet-qr-code.blade.php
https://app.clickup.com/t/86dtf56zf
Also updates the wrong network tooltip text
> refactor: update qr code arkconnect modal

- resources/views/components/arkconnect/modal/install-wallet.blade.php
https://app.clickup.com/t/86dtf5d5z
> refactor: hide install button if not supported

- resources/lang/en/pages.php
- resources/views/components/delegates/arkconnect/resigned-delegate-notice.blade.php
- resources/views/components/delegates/arkconnect/standby-delegate-notice.blade.php
- resources/views/components/delegates/arkconnect/vote-link.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/delegates/vote-link.blade.php
- resources/views/components/tables/rows/mobile/encapsulated/delegates/vote-link.blade.php
- resources/views/components/wallet/overview/delegate.blade.php
- resources/views/livewire/delegates/delegates.blade.php
- resources/views/livewire/delegates/tabs.blade.php
https://app.clickup.com/t/86dtf55fv
> refactor: delegates page standby notice

- resources/views/livewire/wallet-qr-code.blade.php
https://app.clickup.com/t/86dtf56zf
> refactor: disable arkconnect qr tooltip with amount

- package.json
https://app.clickup.com/t/86dtf7tba
> chore: remove pnpm preinstall requirement

- docker/entrypoint.sh
- ~adds `--ignore-scripts` for now due to the pnpm check in our `package.json`~
- adds build step to docker to build the js files
> fix: build files for docker

- app/Services/ArkVaultUrlBuilder.php
- tests/Unit/Services/ArkVaultUrlBuilderTest.php
https://app.clickup.com/t/86dtfjwet
> refactor: use arkscan nethash for arkvault url

- tests/Feature/Http/Livewire/WalletQrCodeTest.php
- tests/Unit/Services/Blockchain/NetworkTest.php
https://app.clickup.com/t/86dtfjwet
related to #887 
> test: remove hardcoded nethash references

- resources/views/components/arkconnect/modal/install-wallet.blade.php
- resources/views/components/arkconnect/modal/modal.blade.php
https://app.clickup.com/t/86dtfxg30
> refactor: arkconnect modal adjustments

- tests/Unit/Console/Commands/CacheValidatorStatisticsTest.php
https://app.clickup.com/t/86dtfjrk2
> test: fix intermittently failing statistics command test

- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dtfjttn
> test: fix intermittently failing transaction type coverage

- tests/Feature/Http/Livewire/DelegateDataBoxesTest.php
- tests/Helpers.php
https://app.clickup.com/t/86dtf5eum
> test: fix intermittently failing delegate databox tests

- resources/js/wallet.js
- resources/lang/en/general.php
- resources/views/components/general/dropdown/list-item.blade.php
- resources/views/components/navbar/arkconnect.blade.php
https://app.clickup.com/t/86dtgpxng
> refactor: arkconnect dropdown my address

- app/Http/Livewire/TransactionTable.php
- tests/Feature/Http/Livewire/TransactionTableTest.php
https://app.clickup.com/t/86drb73fz
> refactor: transactions webhooks

- tests/Analysis/AnalysisTest.php
- tests/Feature/Http/Livewire/DelegateDataBoxesTest.php
- tests/Helpers.php
https://app.clickup.com/t/86dtjkrxv
To test:
Keep running `./vendor/bin/pest tests/Feature/Http/Livewire/DelegateDataBoxesTest.php --filter "should calculate missed correctly with current round"` on the develop branch until it fails
Note: you can try my [`loop`](https://github.com/alexbarnsley/dotfiles/blob/master/bin/loop) command which will keep running until a failure
-   [ ] I added a short description on how …
> test: fix intermittently failing

- WEBHOOKS.md
https://app.clickup.com/t/86dtgqabj
> chore: update webhooks documentation

- resources/js/wallet.js
https://app.clickup.com/t/86dtk8ewj
> refactor: arkconnect handle delegate property naming change

- resources/views/components/navbar/arkconnect.blade.php
https://app.clickup.com/t/86dtgqwbx
> refactor: arkconnect update wrong network address color

- app/Console/Commands/CachePrices.php
- app/Events/CurrencyUpdate.php
- app/Events/NewEntity.php
- app/Http/Livewire/Home/PriceTicker.php
- app/Http/Livewire/Navbar/PriceTicker.php
- app/Http/Livewire/Webhooks/CurrencyUpdate.php
- resources/js/webhooks.js
- resources/views/components/webhooks/reload-blocks.blade.php
- resources/views/components/webhooks/reload-transactions.blade.php
- resources/views/components/webhooks/reload-voters.blade.php
- resources/views/layouts/app.blade.php
- resources/views/livewire/home/price-ticker.blade.php
- resources/views/livewire/navbar/price-ticker.blade.php
- resources/views/livewire/webhooks/currency-update.blade.php
- tests/Unit/Console/Commands/CachePricesTest.php
https://app.clickup.com/t/86drb73g8
> feat: websockets price updates

- app/Contracts/Network.php
- app/Facades/Network.php
- app/Services/ArkVaultUrlBuilder.php
- app/Services/Blockchain/Network.php
- config/arkscan.php
- tests/Feature/Http/Livewire/WalletQrCodeTest.php
- tests/Unit/ViewModels/WalletViewModelTest.php
Related to https://app.clickup.com/t/86dtgpwc0
Depends on: https://github.com/ArdentHQ/arkvault/pull/503
Adds the coin needed for deeplinking Mainsail network
Note im not sure if `mainsail-develop` is the right base branch im assuming it is because is the one that contain mainsail devnet @ItsANameToo  …
> fix: adjust deeplink parameters

- app/Services/Monitor/ForgingInfoCalculator.php
- app/Services/Monitor/ValidatorTracker.php
- tests/Feature/Http/Livewire/ValidatorDataBoxesTest.php
- tests/Helpers.php
- tests/Unit/Console/Commands/CacheMarketDataStatisticsTest.php
- tests/Unit/Services/Monitor/ValidatorTrackerTest.php
https://app.clickup.com/t/86dttf86q
> fix: validator monitor missed blocks lag

- app/ViewModels/WalletViewModel.php
- composer.json
- composer.lock
- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86dtvrh7x
To test, make sure `ARKSCAN_VAULT_URL="https://arkvault-git-feat-mainsail-ardent.vercel.app/#/"` is in your `.env` as the current live ARK Vault doesn't handle mainsail just yet
> fix: mainsail vote url

- README.md
- app/Providers/AppServiceProvider.php
- config/web.php
- docker/production/deploy-prod.sh
- resources/lang/en/general.php
- resources/lang/en/pages.php
- resources/views/components/navbar/logo.blade.php
https://app.clickup.com/t/86dtvcfec
> chore: rename ARKScan to ARK Scan

- app/Events/Concerns/ShouldBeUniqueEvent.php
- app/Events/Statistics/StatisticsUpdate.php
- app/Events/WebsocketEvent.php
- app/Http/Livewire/Stats/Insights.php
https://app.clickup.com/t/86dtwxpzh
> fix: statistics event refresh

- app/Services/Addresses/Aggregates/LatestWalletAggregate.php
- tests/Unit/Services/Addresses/Aggregates/LatestWalletAggregateTest.php
https://app.clickup.com/t/86du1ey25
I tried doing it as a single query but it was super slow, splitting them up saved time
> refactor: latest wallet handle multipayment

- resources/views/vendor/ark/errors/404.blade.php
https://app.clickup.com/t/86du2gj4z
> refactor: update 404 text color

- resources/views/components/navbar/logo.blade.php
https://app.clickup.com/t/86dtvcfec
> fix: remove space in site logo

- docker/nginx-default.conf
https://app.clickup.com/t/86du3pywx
> fix: nginx url configuration

- app/Contracts/Network.php
- app/Facades/Network.php
- app/Services/ArkVaultUrlBuilder.php
- app/Services/Blockchain/Network.php
- app/Services/Monitor/ForgingInfoCalculator.php
- app/Services/Monitor/ValidatorTracker.php
- app/ViewModels/WalletViewModel.php
- composer.json
- composer.lock
- config/arkscan.php
- docker/nginx-default.conf
- tests/Feature/Http/Livewire/ValidatorDataBoxesTest.php
- tests/Feature/Http/Livewire/Validators/MonitorTest.php
- tests/Feature/Http/Livewire/WalletQrCodeTest.php
- tests/Helpers.php
- tests/Unit/Console/Commands/CacheMarketDataStatisticsTest.php
- tests/Unit/Console/Commands/CacheValidatorStatisticsTest.php
- tests/Unit/Services/Monitor/ValidatorTrackerTest.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
- tests/Unit/ViewModels/WalletViewModelTest.php
> chore: merge mainsail-develop into mainsail

- README.md
- app/Console/Commands/FetchExchangesDetails.php
- app/Console/Kernel.php
- app/Providers/AppServiceProvider.php
- composer.json
- composer.lock
- config/web.php
- docker/nginx-default.conf
- docker/production/deploy-prod.sh
- resources/lang/en/general.php
- resources/lang/en/pages.php
- resources/views/vendor/ark/errors/404.blade.php
- tests/Unit/Console/Commands/FetchExchangesDetailsTest.php
https://app.clickup.com/t/86du4vwp8
> chore: merge develop to websockets

- WEBSOCKETS.md
> chore: add basic forge instructions for websockets setup

- app/Console/Commands/CacheValidatorAggregates.php
- app/Console/Commands/CacheValidatorPerformance.php
- app/Console/Commands/CacheValidatorStatistics.php
- app/Http/Livewire/WalletBlockTable.php
- app/Models/Block.php
- app/Models/Wallet.php
- app/Services/Monitor/Aggregates/ValidatorTotalAggregates.php
- app/ViewModels/Concerns/Block/HasValidator.php
- database/factories/BlockFactory.php
- tests/Feature/Http/Livewire/BlockTableTest.php
- tests/Feature/Http/Livewire/Modals/ExportBlocksTest.php
- tests/Feature/Http/Livewire/Navbar/SearchTest.php
- tests/Feature/Http/Livewire/SearchModalTest.php
- tests/Feature/Http/Livewire/Validators/MonitorTest.php
- tests/Feature/Http/Livewire/WalletBlockTableTest.php
- tests/Helpers.php
- tests/Unit/Models/BlockTest.php
- tests/Unit/Services/Monitor/Aggregates/TotalValidatorAggregateTest.php
- tests/Unit/ViewModels/BlockViewModelTest.php
- tests/Unit/ViewModels/WalletViewModelTest.php
- tests/migrations/2020_10_19_042053_create_blocks_table.php
https://app.clickup.com/t/86duufu74
This does not adjust every instance, as some require more changes to get it working. For these there are separate cards:
- https://app.clickup.com/t/86duuvc8u
- https://app.clickup.com/t/86duuvbz0
- https://app.clickup.com/t/86duuvbtv
- https://app.clickup.com/t/86duuvb4m
-   [ ] Documentation _(if …
> refactor: use generator_address instead of generator_public_key

- app/Models/Block.php
- database/factories/BlockFactory.php
https://app.clickup.com/t/86duuvb4m
> refactor: add total gas used column

- app/Http/Livewire/Validators/Validators.php
- app/ViewModels/Concerns/Wallet/HasVoters.php
https://app.clickup.com/t/86duu67md
I've commented out all the database logic, and put a fix in place to handle no values for validatorVoteBalance
> refactor: get initial validators page working

- app/ViewModels/Concerns/Transaction/HasPayload.php
- app/ViewModels/TransactionViewModel.php
- resources/lang/en/actions.php
- resources/lang/en/pages.php
- resources/views/components/transaction/code-block/code-block.blade.php
- resources/views/components/transaction/code-block/tab.blade.php
- resources/views/components/transaction/page/more-details.blade.php
- tailwind.config.js
- tests/Unit/ViewModels/TransactionViewModelTest.php
- tests/migrations/2020_10_19_042053_create_blocks_table.php
https://app.clickup.com/t/86dur5qr0
> feat: transaction code block

- app/ViewModels/Concerns/Transaction/HasPayload.php
- resources/lang/en/contracts.php
- resources/views/components/transaction/code-block/formatted-contract.blade.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86duw2g6z
> refactor: default evm contract formatting

- app/Console/Commands/CacheUsernames.php
- app/Console/Commands/CacheValidatorStatistics.php
- app/Console/Commands/CacheValidatorVoterCounts.php
- app/Http/Livewire/Stats/Insights.php
- app/Http/Livewire/Validators/Concerns/HandlesMonitorDataBoxes.php
- app/Services/Cache/StatisticsCache.php
- app/Services/Cache/WalletCache.php
- app/ViewModels/Concerns/Wallet/CanBeValidator.php
- app/ViewModels/Concerns/Wallet/CanForge.php
- app/ViewModels/Concerns/Wallet/HasVoters.php
- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
- tests/Feature/Http/Livewire/Validators/HeaderStatsTest.php
- tests/Feature/Http/Livewire/Validators/MonitorTest.php
- tests/Feature/Http/Livewire/Validators/ValidatorsTest.php
- tests/Helpers.php
- tests/Unit/Console/Commands/CacheUsernamesTest.php
- tests/Unit/Console/Commands/CacheValidatorStatisticsTest.php
- tests/Unit/Console/Commands/CacheValidatorWalletsTest.php
- tests/Unit/Console/Commands/CacheValidatorsWithVotersTest.php
- tests/Unit/Services/Cache/WalletCacheTest.php
- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86duuvbz0
There will be some failing tests as a result of this. To save going down a rabbit hole there are some areas I have left in the way blocks are created during tests
> refactor: update cache public key usage

- app/Jobs/BuildForgingStats.php
- app/Models/Webhook.php
- app/Providers/HorizonServiceProvider.php
- composer.json
- composer.lock
- package.json
- pnpm-lock.yaml
- tests/Analysis/AnalysisTest.php
https://app.clickup.com/t/86dt2kdub
requires https://github.com/ArkEcosystem/laravel-foundation/pull/625
> feat: upgrade dependencies incl laravel

- .github/workflows/ci.yml
- .github/workflows/deps.yml
- .github/workflows/ui.yml
- composer.json
- composer.lock
https://app.clickup.com/t/86dt2kdub
> chore: update php requirement to 8.3

- composer.json
- composer.lock
https://app.clickup.com/t/86dt2kdub
> refactor: re-add missing reverb dependency

- app/Http/Livewire/Validators/Validators.php
- app/ViewModels/Concerns/Wallet/CanBeValidator.php
- app/ViewModels/Concerns/Wallet/CanVote.php
- resources/views/components/clipboard.blade.php
- resources/views/components/compatible-wallets/learn-more.blade.php
- resources/views/components/general/dropdown/filter.blade.php
- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
- resources/views/components/general/pagination/includes/arrow.blade.php
- resources/views/components/stats/periods-selector.blade.php
- resources/views/components/tables/headers/desktop/address.blade.php
- resources/views/components/tables/headers/desktop/id.blade.php
- resources/views/components/tables/headers/desktop/includes/livewire-sort-icon.blade.php
- resources/views/components/tables/headers/desktop/number.blade.php
- resources/views/components/tables/headers/desktop/sortable-header.blade.php
- resources/views/components/tables/mobile/top-accounts.blade.php
- resources/views/components/tables/mobile/validators/list-table.blade.php
- resources/views/components/tables/mobile/validators/monitor.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/amount.blade.php
- resources/views/components/tables/rows/desktop/validators/monitor-row.blade.php
- resources/views/components/tables/rows/mobile/encapsulated/age.blade.php
- resources/views/components/transaction/code-block/code-block.blade.php
- resources/views/components/validators/arkconnect/vote-link.blade.php
- resources/views/components/validators/vote-link.blade.php
- resources/views/livewire/navbar/search.blade.php
https://app.clickup.com/t/86duu67md
To test, run the below:
```
php artisan migrate:fresh --seed
php artisan explorer:forging-stats:build
php artisan explorer:cache-validator-productivity
php artisan explorer:cache-validator-performance
php artisan explorer:cache-usernames  
php artisan explorer:cache-validator-wallets 
php artisan explorer:cache-validators-with-voters 
php artisan explorer:cache-validator-voter-counts
```
or below for a one-liner :sweat_smile: 
```
php artisan migrate:fresh --seed && php artisan explorer:forging-stats:build && php artisan explorer:cache-validator-productivity && php artisan explorer:cache-validator-performance && php artisan explorer:cache-usernames && php artisan explorer:cache-validator-wallet && php artisan explorer:cache-validators-with-voter && php …
```
> refactor: validators page

- resources/lang/en/contracts.php
https://app.clickup.com/t/86dv3hkrw
> chore: update contract method ids

- app/Http/Livewire/TransactionTable.php
- app/Http/Livewire/WalletTransactionTable.php
- app/Models/Transaction.php
https://app.clickup.com/t/86dv417uq
requires https://github.com/ArdentHQ/arkscan/pull/988 before the Transactions page will work
> refactor: remove transaction filters

- app/Http/Livewire/WalletTransactionTable.php
- app/Models/Wallet.php
https://app.clickup.com/t/86dv417pt
> fix: wallet page error

- app/Console/Commands/CacheUsernames.php
https://app.clickup.com/t/86dv41897
> refactor: remove forget username logic

- app/Models/Transaction.php
- app/Services/Transactions/TransactionDirection.php
- app/ViewModels/Concerns/Transaction/InteractsWithWallets.php
- app/ViewModels/TransactionViewModel.php
https://app.clickup.com/t/86dv419mq
TODO:
> fix: search transaction indexing

- app/Console/Commands/CacheNetworkAggregates.php
https://app.clickup.com/t/86dv41aj3
> refactor: remove validator registration scope for cache networks command

- app/Console/Commands/CacheValidatorResignationIds.php
https://app.clickup.com/t/86dv41em0
> refactor: remove validator scope for cache resignations command

- app/Services/Addresses/Aggregates/LatestWalletAggregate.php
https://app.clickup.com/t/86dv421tn
> refactor: adjust columns in latest wallet aggregate

- resources/views/components/transaction/page/addressing.blade.php
https://app.clickup.com/t/86dv4f3wj
This outputs the recipient address on the transaction page. Based on the designs/conversations, I've left "Contract" as is in the transaction listing.
> refactor: output contract address

- app/Models/Receipt.php
- app/ViewModels/Concerns/Transaction/HasPayload.php
- app/ViewModels/Concerns/Transaction/InteractsWithWallets.php
https://app.clickup.com/t/86dv7j03d
@ItsANameToo I've set the recipient to the deployed contract address - I couldn't find if that was correct :thinking: 
> fix: payload formatting for unknown contracts

- app/ViewModels/TransactionViewModel.php
- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
- resources/views/components/transaction/amount.blade.php
- resources/views/components/transaction/page/summary.blade.php
https://app.clickup.com/t/86dv4f3vd
To test with currencies:
- Update .env with the below:
```
ARKSCAN_NETWORK=production
ARKSCAN_NETWORK_CAN_BE_EXCHANGED=true
ARKSCAN_NETWORK_CURRENCY="ARK" # Probably not necessary
```
- run `php artisan explorer:cache-currencies-data` - you may need to run it a few times due to coingecko throttling
-   [ …
> refactor: transaction amounts

- app/Http/Livewire/Validators/Validators.php
https://app.clickup.com/t/86dv7evgd
> refactor: re-add validator rank for listing

- app/Console/Commands/CacheGasTrackerData.php
- app/Console/Kernel.php
- app/Services/Cache/MainsailCache.php
- app/Services/MainsailApi.php
- config/arkscan.php
- tests/Unit/Console/Commands/CacheGasTrackerDataTest.php
- tests/Unit/Services/Cache/MainsailCacheTest.php
- tests/Unit/Services/MainsailApiTest.php
https://app.clickup.com/t/86dv4rbnk
TODO:
> feat: cache gas tracker data

- app/Services/Transactions/TransactionMethod.php
https://app.clickup.com/t/86dv7rgp0
> refactor: handle known contract names for method

- resources/views/components/tables/rows/desktop/encapsulated/validators/validator-status.blade.php
https://app.clickup.com/t/86dv4f3wt
> refactor: update resigned status on validators page

- app/ViewModels/Concerns/Transaction/HasState.php
- resources/views/components/tables/rows/desktop/encapsulated/transaction-id.blade.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
- tests/migrations/2020_10_19_042110_create_transactions_table.php
https://app.clickup.com/t/86dv5zkhg
> refactor: transaction id status

- app/DTO/MemoryWallet.php
- app/Facades/Network.php
- app/Services/Blockchain/Network.php
- config/arkscan.php
- tests/Unit/Services/Blockchain/NetworkTest.php
https://app.clickup.com/t/86dv8cxdg
> fix: handle known contracts per network

- app/ViewModels/Concerns/Transaction/CanBeValidatorRegistration.php
- app/ViewModels/Concerns/Transaction/HasPayload.php
- app/ViewModels/TransactionViewModel.php
- resources/views/components/transaction/page/transaction-type.blade.php
https://app.clickup.com/t/86dv8my2u
> refactor: show validator bls public key for registrations

- app/Console/Commands/CacheKnownWallets.php
- app/Contracts/Network.php
- app/Facades/Network.php
- app/Services/Blockchain/Network.php
- tests/Helpers.php
https://app.clickup.com/t/86dv9xeh8
> refactor: only request known wallets in command

- resources/views/components/transaction/code-block/code-block.blade.php
https://app.clickup.com/t/86dv8r4bp
> refactor: codeblock copy code styling

- resources/css/_theme.css
- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/addressing.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/transaction-id.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/validators/missed-blocks.blade.php
- tailwind.config.js
https://app.clickup.com/t/86dv8gn0a
> refactor: move hardcoded theme colours

- resources/views/components/home/header.blade.php
- resources/views/livewire/home/statistics.blade.php
https://app.clickup.com/t/86dva2t70
> refactor: home mobile gas tracker slider

- app/Http/Livewire/Validators/RecentVotes.php
- app/Models/Concerns/Transaction/CanBeSorted.php
- resources/views/components/tables/desktop/validators/recent-votes.blade.php
- resources/views/components/tables/mobile/validators/recent-votes.blade.php
- resources/views/components/tables/rows/mobile/encapsulated/validators/vote-address.blade.php
- resources/views/components/transaction/page/transaction-type.blade.php
https://app.clickup.com/t/86dvb57fv
> refactor: recent votes handling

- .github/workflows/ci.yml
- database/factories/TransactionFactory.php
- tests/Feature/Http/Livewire/BlockTableTest.php
Fixes tests  on tests/Feature/Http/Livewire/BlockTableTest.php (and possibly other parts) and  encoding issues https://app.clickup.com/t/86dv9e9nf
https://app.clickup.com/t/86dvc7z1m
> fix: block table tests & transaction factory encoding

- database/factories/TransactionFactory.php
- tests/Feature/Http/Controllers/ShowTransactionControllerTest.php
- tests/migrations/2020_10_19_042110_create_transactions_table.php
https://app.clickup.com/t/86dvcq6wg
> fix: show transaction controller tests

- tests/Unit/Services/Transactions/Aggregates/Fees/Historical/DayAggregateTest.php
- tests/Unit/Services/Transactions/Aggregates/Fees/Historical/MonthAggregateTest.php
- tests/Unit/Services/Transactions/Aggregates/Fees/Historical/QuarterAggregateTest.php
- tests/Unit/Services/Transactions/Aggregates/Fees/Historical/RangeAggregateTest.php
- tests/Unit/Services/Transactions/Aggregates/Fees/Historical/WeekAggregateTest.php
- tests/Unit/Services/Transactions/Aggregates/Fees/Historical/YearAggregateTest.php
https://app.clickup.com/t/86dvcx3uu
> test: transaction historical fee aggregates

- tests/Feature/Http/Controllers/TransactionsControllerTest.php
https://app.clickup.com/t/86dvcww9u
> fix: transactions controller tests

- database/factories/TransactionFactory.php
https://app.clickup.com/t/86dv9e9nf
To test (developer):
Create or edit a test, and use the below:
```
$validator = Wallet::factory()->activeValidator()->create();
$transactions = Transaction::factory(4)->vote($validator->address)->create();
dd($transactions->pluck('data')->map(fn ($data) => bin2hex(stream_get_contents($data, offset: 0))));
```
-   [ ] I added a short description on how to test this PR _(if …
> test: fix data stream when creating multiple records

- tests/Feature/Http/Controllers/WebhooksControllerTest.php
https://app.clickup.com/t/86dvcydry
> fix: webhook controller test

- tests/Unit/ViewModels/BlockViewModelTest.php
https://app.clickup.com/t/86dvd06vw
> fix: block view model test

- app/Models/Transaction.php
- tests/Unit/Console/Commands/CacheFeesTest.php
https://app.clickup.com/t/86dvcx319
> test: cache fees command updates

- tests/Feature/Http/Livewire/Home/StatisticsTest.php
- tests/Feature/Http/Livewire/Home/TransactionsTest.php
https://app.clickup.com/t/86dvcx28m
> test: home transactions & statistics components

- tests/Helpers.php
- tests/Unit/Console/Commands/CacheValidatorAggregatesTest.php
- tests/Unit/Console/Commands/CacheValidatorPerformanceTest.php
- tests/Unit/Console/Commands/CacheValidatorsWithVotersTest.php
https://app.clickup.com/t/86dvcx2g6
There are issues with some of the tests which I think require a larger rewrite - https://app.clickup.com/t/86dvd87y3
> test: update cache validator tests & fix mock round creation

- app/Repositories/TransactionRepository.php
https://app.clickup.com/t/86dvcx3p7
Created a card relating to other properties used in the TransactionRepository - https://app.clickup.com/t/86dvd9jec
> refactor: rename recipient_id column in transaction repository

- tests/Unit/DTO/MemoryWalletTest.php
- tests/Unit/DTO/SlotTest.php
https://app.clickup.com/t/86dvcx3dr
> test: fix dto tests

- tests/Unit/Jobs/Webhooks/CheckLargestTransactionTest.php
- tests/Unit/Jobs/Webhooks/CheckLatestWalletTest.php
https://app.clickup.com/t/86dvcx3fv
> test: webhook jobs

- database/factories/TransactionFactory.php
- tests/Feature/Http/Livewire/__stubs/NetworkStub.php
- tests/Unit/Console/Commands/CacheTransactionsTest.php
https://app.clickup.com/t/86dvcx332
Added a card to look at multipayment amounts being included in the totals - https://app.clickup.com/t/86dvdvux1
> test: fix cache transactions command tests

- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86dvdkvbv
> fix: wallet view model tests

- tests/Unit/ViewModels/ForgingStatsViewModelTest.php
https://app.clickup.com/t/86dve1jgz
> fix: forging state view model tests

- tests/Unit/ViewModels/BlockViewModelTest.php
Fixes two new errors that appeared after recent changes
https://app.clickup.com/t/86dvd06vw
> fix: block view model tests

- app/Models/Concerns/ForgingStats/CanBeSorted.php
- tests/Feature/Http/Livewire/Validators/MissedBlocksTest.php
Replaces https://github.com/ArdentHQ/arkscan/pull/1064
Closes https://app.clickup.com/t/86dvcxem4
> fix: missed block tests

- tests/Unit/Console/Commands/CacheAddressStatisticsTest.php
https://app.clickup.com/t/86dvcx2xr
> test: cache address statistics command

- tests/Unit/Jobs/CacheBlocksTest.php
https://app.clickup.com/t/86dvcx3f5
> test: cache blocks command

- database/factories/TransactionFactory.php
- tests/Unit/Services/Transactions/Aggregates/Type/VoteAggregateTest.php
https://app.clickup.com/t/86dvcx3vv
> test: transaction aggregates by type

- tests/Unit/Services/Transactions/Aggregates/LargestTransactionAggregateTest.php
https://app.clickup.com/t/86dvcx3wv
> test: largest transaction aggregate

- app/Http/Livewire/Concerns/ChartNumberFormatters.php
- app/Services/Cache/FeeCache.php
- app/Services/Transactions/Aggregates/Fees/LastFeeAggregate.php
- database/factories/TransactionFactory.php
- tests/Feature/Http/Livewire/BlockTableTest.php
- tests/Feature/Http/Livewire/Stats/AllTimeFeesTest.php
- tests/Feature/Http/Livewire/Stats/CurrentAverageFeeTest.php
- tests/Feature/Http/Livewire/Stats/InsightsTest.php
- tests/Feature/Http/Livewire/TransactionTableTest.php
- tests/Feature/Http/Livewire/WalletTransactionTableTest.php
https://app.clickup.com/t/86dvcx2e5
> test: livewire components

- tests/Unit/Repositories/WalletRepositoryTest.php
- tests/Unit/Repositories/WalletRepositoryWithCacheTest.php
https://app.clickup.com/t/86dvcx3q0
> fix: wallet repository test

- tests/Unit/Services/Transactions/TransactionMethodTest.php
- tests/Unit/Services/Transactions/TransactionStateIconTest.php
- tests/Unit/Services/Transactions/TransactionStateTest.php
https://app.clickup.com/t/86dvcx3yk
> fix: services transactions tests

- app/Services/Cache/RequestScopedCache.php
https://app.clickup.com/t/86dvcx4d9
> fix: analysis test

- tests/Unit/Services/Addresses/Aggregates/LatestWalletAggregateTest.php
https://app.clickup.com/t/86dvcx3t3
> test: latest wallet aggregate

- app/Http/Livewire/Validators/Monitor.php
- tests/Feature/Http/Livewire/Validators/MonitorTest.php
https://app.clickup.com/t/86dvcxen2
> fix: livewire validators monitor test

- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
Fixes everything except for the `can lookup wallets by the username` test for which I added a [new ticket](https://app.clickup.com/t/86dveraxr)
https://app.clickup.com/t/86dver993
> fix: show wallet controller test

- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
https://app.clickup.com/t/86dvdmpme
> test: skip username redirection test

- tests/TestCase.php
https://app.clickup.com/t/86dve2448
> test: fix forging stats migrations

- tests/Feature/Http/Livewire/Navbar/SearchTest.php
https://app.clickup.com/t/86dve33zq
> fix: navbar search test

- app/Console/Commands/CacheAnnualStatistics.php
- app/Services/BigNumber.php
- database/factories/TransactionFactory.php
- tests/Unit/Console/Commands/CacheAnnualStatisticsTest.php
https://app.clickup.com/t/86dvcx2zr
> fix: cache annual statistics test

- app/ViewModels/WalletViewModel.php
- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86dvdxm73
> fix: public key popup handle empty string

- tests/Unit/Console/Commands/CacheValidatorVoterCountsTest.php
https://app.clickup.com/t/86dvd8bhg
> fix: cache validator voter counts tests

- resources/js/table-sorting.js
- resources/views/components/tables/desktop/validators/monitor.blade.php
- resources/views/components/tables/headers/desktop/sortable-header.blade.php
https://app.clickup.com/t/86dv34k3y
> fix: validator monitor alpinejs errors

- tests/Feature/Http/Livewire/Validators/ValidatorsTest.php
https://app.clickup.com/t/86dvcxewe
> fix: validators test

- tests/TestCase.php
- tests/Unit/Services/Transactions/TransactionDirectionTest.php
https://app.clickup.com/t/86dvf9jzx
> fix: transaction direction test

- tests/Unit/Services/Transactions/TransactionDirectionIconTest.php
https://app.clickup.com/t/86dvf9m9w
> fix: transaction direction icon test

- tests/Unit/Console/Commands/CacheFeesTest.php
https://app.clickup.com/t/86dvf9mcf
> fix: cache fees test

- tests/TestCase.php
Rollback the changes from this PR https://github.com/ArdentHQ/arkscan/pull/1081 as it created a bunch of new errors on the tests, see [ticket comments](https://app.clickup.com/t/86dve2448) for details
> revert: fix for forging stats migrations

- tests/Unit/Jobs/Webhooks/CheckLatestWalletTest.php
https://app.clickup.com/t/86dvf9yxn
> test: fix check latest wallet webhook job

- tests/Feature/Http/Controllers/WebhooksControllerTest.php
https://app.clickup.com/t/86dvcydry
> test: fix unique addresses event webhook test

- .github/workflows/ci.yml
- .gitignore
- tests/Analysis/AnalysisTest.php
- tests/Feature/Http/Livewire/TransactionTableTest.php
- tests/Feature/Http/Livewire/Validators/MonitorTest.php
- tests/Helpers.php
- tests/Unit/Console/Commands/ImportCommandTest.php
- tests/Unit/Console/Commands/ScoutPauseIndexingTest.php
- tests/Unit/Console/Commands/ScoutResumeIndexingTest.php
- tests/Unit/Jobs/IndexBlocksTest.php
- tests/Unit/Jobs/IndexTransactionsTest.php
- tests/Unit/Jobs/IndexWalletsTest.php
https://app.clickup.com/t/86dvfwjt6
> fix: caching issue on tests

- app/ViewModels/TransactionViewModel.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dvfy90g
> fix: transaction view model coverage

- tests/Unit/Services/Blockchain/NetworkTest.php
https://app.clickup.com/t/86dvfy81z
> fix: blockchain network service coverage

- app/DTO/MemoryWallet.php
https://app.clickup.com/t/86dvgbmp2
> fix: dto memory wallet coverage

- resources/views/components/clipboard.blade.php
- resources/views/components/compatible-wallets/learn-more.blade.php
- resources/views/components/delegates/arkconnect/vote-link.blade.php
- resources/views/components/delegates/vote-link.blade.php
- resources/views/components/general/dropdown/filter.blade.php
- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
- resources/views/components/general/pagination/includes/arrow.blade.php
- resources/views/components/stats/periods-selector.blade.php
- resources/views/components/tables/desktop/delegates/monitor.blade.php
- resources/views/components/tables/headers/desktop/address.blade.php
- resources/views/components/tables/headers/desktop/id.blade.php
- resources/views/components/tables/headers/desktop/includes/livewire-sort-icon.blade.php
- resources/views/components/tables/headers/desktop/number.blade.php
- resources/views/components/tables/headers/desktop/sortable-header.blade.php
- resources/views/components/tables/mobile/delegates/list-table.blade.php
- resources/views/components/tables/mobile/delegates/monitor.blade.php
- resources/views/components/tables/mobile/top-accounts.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/amount.blade.php
- resources/views/components/tables/rows/mobile/encapsulated/age.blade.php
- resources/views/livewire/navbar/search.blade.php
- tests/Unit/Console/Commands/CacheMarketDataStatisticsTest.php
https://app.clickup.com/t/86dvkykv5
> chore: trigger rustywind & fix failing tests

- tests/Unit/Models/TransactionTest.php
https://app.clickup.com/t/86dvkyxxk
> fix: models transaction test coverage

- tests/Unit/Models/StateTest.php
https://app.clickup.com/t/86dvkzevr
> fix: add state model test coverage

- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dvfy8q7
> fix: test transaction view model username method

- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86dvfy8yn
> fix: has voters trait test coverage

- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dvfy8xz
> fix: transaction view model receipt test coverage

- app/ViewModels/Concerns/Transaction/InteractsWithVotes.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dvfy8um
> fix: transaction view model voted tests

- app/ViewModels/Concerns/Transaction/HasPayload.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dvfy8tf
> fix: has payload coverage

- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dvfy8r6
> fix: has method trait coverage

- app/ViewModels/Concerns/Transaction/CanBeValidatorRegistration.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dvfy8p0
> fix: can be validator registration coverage

- tests/Unit/Services/Transactions/TransactionMethodTest.php
https://app.clickup.com/t/86dvfy8nf
> fix: transaction method coverage

- tests/Unit/Jobs/CacheBlocksTest.php
https://app.clickup.com/t/86dvkyvue
> fix: cache blocks coverage

- app/Console/Commands/CacheAddressStatistics.php
- tests/Unit/Console/Commands/CacheAddressStatisticsTest.php
https://app.clickup.com/t/86dvkythv
> fix: cache address statistics test flaky

- app/Services/Cache/Concerns/ManagesCache.php
https://app.clickup.com/t/86dvfy8j7
> fix: manages cache trait test coverage

- resources/lang/en/metatags.php
https://app.clickup.com/t/86dvcj13y
> refactor: add error 500 meta title

- app/Http/Livewire/Concerns/HasTablePagination.php
https://app.clickup.com/t/86dvmmc69
> fix: pagination error 500

- app/Http/Livewire/Validators/Monitor.php
https://app.clickup.com/t/86dvnuzcb
> test: ignore code coverage on monitor component

- app/Console/Commands/CacheMarketDataStatistics.php
- app/Console/Commands/PopulateHistoricVolume.php
- tests/Unit/Console/Commands/CacheMarketDataStatisticsTest.php
- tests/Unit/Console/Commands/PopulateHistoricVolumeTest.php
https://app.clickup.com/t/86dvfgfj7
replaces https://github.com/ArdentHQ/arkscan/pull/1102
> refactor: populate volume from historic data

- app/Console/Commands/CachePrices.php
- tests/Unit/Console/Commands/CachePricesTest.php
https://app.clickup.com/t/86dvn20kv
> fix: price charts showing all prices

- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
https://app.clickup.com/t/86dv24qrd
> fix: show negative sign for outgoing multipayment

- resources/js/wallet.js
Error seems to happen only for cases where the wallet does not exist on the network yet
https://app.clickup.com/t/86dv9gxbq
> fix: error after connecting extension

- app/Exceptions/Handler.php
- composer.json
- composer.lock
https://app.clickup.com/t/86dvpypwj
> fix: upgrade foundation with theme bug patch

- app/Http/Livewire/Validators/Monitor.php
- tests/Feature/Http/Livewire/Validators/MonitorTest.php
https://app.clickup.com/t/86dvgbptg
> test: validator monitor coverage

- resources/js/api/blocks.js
https://app.clickup.com/t/86dvpfp06
> fix: blocks export

- resources/lang/en/pages.php
- resources/views/app/statistics.blade.php
- resources/views/components/stats/fee-card.blade.php
- resources/views/livewire/stats/gas-tracker.blade.php
https://app.clickup.com/t/86dvqtd8v
> refactor: improve gas fee in stats

- resources/js/transactions-export.js
https://app.clickup.com/t/86dvruwph
Also adds the fee (gas price) that wasnt being handled properly 
> fix: add recipient and sender on transaction export

- resources/views/components/general/identity.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/address.blade.php
https://app.clickup.com/t/86dvrv1q3 
> fix: multi payment recipient address 

- app/Console/Commands/CacheAnnualStatistics.php
https://app.clickup.com/t/86dvt8201
> fix: phpstan style warning

- app/Services/MainsailApi.php
- tests/Unit/Console/Commands/CacheGasTrackerDataTest.php
- tests/Unit/Services/MainsailApiTest.php
https://app.clickup.com/t/86dv7tt1a
> refactor: remove qa forced fees

- app/Models/Concerns/Transaction/CanBeSorted.php
- tests/Feature/Http/Livewire/Validators/RecentVotesTest.php
https://app.clickup.com/t/86dvt4djg
> refactor: recent votes sort validator with known wallets

- database/migrations/2024_10_14_140202_change_public_key_column_to_address_on_forging_stats_table.php
Noticed whilst working on https://app.clickup.com/t/86dvbygg4
There shouldn't have been commented code committed 
> chore: remove commented code

- resources/lang/en/pages.php
- resources/views/components/general/page-section/confirmations.blade.php
- resources/views/components/transaction/page/status.blade.php
https://app.clickup.com/t/86dvbyk4a
> chore: update confirmations header on tx detail page

- app/Services/Cache/CryptoDataCache.php
- app/Services/MarketDataProviders/CoinGecko.php
- app/Services/MarketDataProviders/CryptoCompare.php
https://app.clickup.com/t/86dvm349z
> refactor: remove unnecessary caching

- tests/Feature/Http/Livewire/Validators/ValidatorsTest.php
https://app.clickup.com/t/86dvv3vea
Not 100% sure what caused this - I looked into the seeder side of things and it looks fine, but truncating data before each test seemed to fix the failures.
> test: fix intermittent validators tests

- tests/Unit/ViewModels/ViewModelFactoryTest.php
https://app.clickup.com/t/86dvv3x07
> test: fix intermittent view model test

- app/Providers/AppServiceProvider.php
- resources/views/livewire/navbar/price-ticker.blade.php
https://app.clickup.com/t/86dvxr046
> chore: remove old todos

- resources/views/components/transaction/page/summary.blade.php
https://app.clickup.com/t/86dvf1ap7
> refactor: show multipayment amount on tx detail

- composer.lock
https://app.clickup.com/t/86dwgnvth
> chore: update foundation

- config/arkscan.php
https://app.clickup.com/t/86dwet58p
> fix: use proxy contract address for multipayments

- resources/js/api/blocks.js
- resources/js/api/transactions.js
- resources/js/blocks-export.js
- resources/js/transactions-export.js
Adjusts the export
https://app.clickup.com/t/86dwh1h44
note: to test set `ARKSCAN_NETWORK_API=http://localhost:4003/api` or whatever is the api you are using
> refactor: adjust exports for upcoming mainsail

- app/Jobs/BuildForgingStats.php
- tests/Unit/Console/Commands/BuildForgingStatsTest.php
https://app.clickup.com/t/86dwerwjc
> fix: missed blocks block height wrong values

- app/Console/Commands/CacheAnnualStatistics.php
- app/Services/Cache/StatisticsCache.php
- composer.lock
- tests/Feature/Http/Controllers/TransactionsControllerTest.php
- tests/Unit/Console/Commands/CacheAnnualStatisticsTest.php
- tests/Unit/Services/Cache/StatisticsCacheTest.php
https://app.clickup.com/t/86dwer19q
> fix: handle decimals on transactions fees

- app/Http/Livewire/WalletTransactionTable.php
- app/ViewModels/Concerns/Transaction/HasPayload.php
- app/ViewModels/TransactionViewModel.php
- config/arkscan.php
- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/amount.blade.php
- resources/views/components/transaction/amount.blade.php
- tests/Unit/ViewModels/TransactionViewModelTest.php
https://app.clickup.com/t/86dweqtm1
> refactor: handle incoming multipayments on wallet transactions

- resources/js/includes/enums.js
- resources/js/transactions-export.js
https://app.clickup.com/t/86dwrwh0h
> refactor: handle bls registration exports

- app/Http/Livewire/BlockTransactionsTable.php
- app/Http/Livewire/TransactionTable.php
- app/Http/Livewire/WalletTransactionTable.php
- app/Models/Scopes/OrderByTimestampScope.php
- app/Models/Scopes/OrderByTransactionIndexScope.php
- tests/Feature/Http/Livewire/BlockTransactionsTableTest.php
- tests/Feature/Http/Livewire/Home/TransactionsTest.php
- tests/Feature/Http/Livewire/WalletTransactionTableTest.php
https://app.clickup.com/t/86dwrbd50
> refactor: sort transactions by index

- app/Http/Livewire/BlockTransactionsTable.php
- app/Http/Livewire/Delegates/MissedBlocks.php
- app/Http/Livewire/Delegates/RecentVotes.php
- app/Http/Livewire/Home/Transactions.php
- app/Http/Livewire/TransactionTable.php
- app/Http/Livewire/WalletTransactionTable.php
- app/Models/Transaction.php
- app/ViewModels/Concerns/Transaction/InteractsWithVotes.php
- tests/Unit/Services/Transactions/TransactionTypeTest.php
https://app.clickup.com/t/86dx5977f
https://app.clickup.com/t/86dx597cb
requires #1228 
> refactor: voted for improvement

- app/Console/Kernel.php
https://app.clickup.com/t/86dvxzg15
> refactor: enable validator performance schedule command

- resources/views/components/transaction/page/more-details.blade.php
https://app.clickup.com/t/86dxd1fkf
> fix: transaction input data container spacing

- app/Http/Livewire/Wallet/Concerns/TransactionsTab.php
https://app.clickup.com/t/86dxg71pj
> refactor: wallet transactions ignore multipayment logic when filtered out

- resources/views/components/tables/mobile/includes/encapsulated.blade.php
https://app.clickup.com/t/86dxfhrm2
> refactor: update no results line height

- resources/views/components/transaction/page/section-detail/address.blade.php
https://app.clickup.com/t/86dxfhrpp
> refactor: update contract badge styling

- app/Models/Scopes/OtherTransactionTypesScope.php
- app/Models/Transaction.php
https://app.clickup.com/t/86dxggh45
> fix: validator update filtering

- resources/views/components/transaction/page/recipients.blade.php
- tests/Feature/Http/Controllers/ShowTransactionControllerTest.php
https://app.clickup.com/t/86dxkbfvx
> fix: multipayment detail page

- resources/inertia/Components/Wallet/Address.tsx
https://app.clickup.com/t/86dxnfee4
> fix: monitor validator link opening

- tests/Feature/Http/Livewire/Validators/Concerns/MissedBlocksTabTest.php
https://app.clickup.com/t/86dxj203n
> test: fix intermittent missed blocks test

- app/ViewModels/TransactionViewModel.php
- resources/views/components/tables/rows/desktop/encapsulated/amount.blade.php
- tests/Feature/Http/Livewire/Wallet/Concerns/TransactionsTabTest.php
https://app.clickup.com/t/86dxp2g2v
> refactor: show resigned unlocked amount

- .gitignore
- package.json
- pnpm-lock.yaml
- resources/inertia/Components/General/Detail.tsx
- resources/inertia/Components/General/Number.tsx
- resources/inertia/Components/Tables/Desktop/Validators/Monitor.tsx
- resources/inertia/Components/Tables/Mobile/Validators/Monitor.tsx
- resources/inertia/Components/Validator/Monitor/HeaderStats.tsx
- resources/inertia/Components/Validator/Monitor/MissedWarning.tsx
- resources/inertia/Components/Validator/Monitor/Status.tsx
- resources/inertia/Pages/Validators/Monitor.tsx
- resources/inertia/i18n.ts
- resources/js/app-inertia.tsx
- vite.config.js
https://app.clickup.com/t/86dxjb6hc
Uses `laravel-react-i18n` for the php to json conversion, and `react-i18next` for the actual translations
> refactor: inertia translation handling
