- app/Exceptions/Sentry.php
- tests/Unit/SentryTest.php
- tests/Unit/Services/ExchangeRateTest.php
https://app.clickup.com/t/2npyb17
For some reason, Laravel's `Str::contains` method no longer ignores casing.
Additionally, I have added rest of the exception messages that cause the Sentry exceptions.
> chore: add additional error messages to be ignored in Sentry

- app/Console/Commands/CachePrices.php
- app/Jobs/CacheCurrenciesHistory.php
- app/Services/Cache/Concerns/ManagesCache.php
- app/Services/Cache/CryptoDataCache.php
- tests/TestCase.php
- tests/Unit/Console/Commands/CacheCurrenciesHistoryTest.php
- tests/Unit/Console/Commands/CachePricesTest.php
- tests/Unit/Jobs/CacheCurrenciesHistoryTest.php
- tests/Unit/Services/MarketDataProviders/CoinGeckoTest.php
Changes the currency jobs to keep the data from a prior run in case an empty response is received
What's left:
> refactor: keep previous historic data on empty response

- app/Http/Livewire/DelegateTabs.php
- database/factories/WalletFactory.php
- tests/Feature/Http/Livewire/DelegateMonitorTest.php
- tests/Feature/Http/Livewire/DelegateTabsTest.php
https://app.clickup.com/t/2ve8qzd
Also updates the delegate tabs functionality to exclude resigned from the standby delegates query
> refactor: update risky tests

- app/Http/Livewire/PriceTicker.php
- resources/views/livewire/price-ticker.blade.php
https://app.clickup.com/t/2vzhqga
> fix: remove loading state when navbar price has loaded

- app/Http/Livewire/Migration/Stats.php
- app/Http/Livewire/Migration/WalletHighlight.php
- tests/Feature/Http/Livewire/Migration/WalletHighlightTest.php
Refactors the component so both (migration page and wallet overview page) use the same logic to calculate the supply
> fix: use correct supply calculation on wallet page

- app/Aggregates/VotePercentageAggregate.php
- tests/Unit/Aggregates/VotePercentageAggregateTest.php
https://app.clickup.com/t/2rycq50
I couldn't determine why the error was happening. From writing tests, it seems that the division by zero occurs when there is no network supply - possibly an infrastructure issue with connecting to the database or caching services? It may also be resolved as I see no recent occurrences of this happening
- …
> fix: handle zero network supply

- app/Models/ForgingStats.php
https://app.clickup.com/t/8677ccyxy
Adds a primary key column to the ForgingStats model to avoid it getting confused when using `updateOrCreate` that defaults to an `id` column otherwise
> fix: add explicit primary key column to forging stats

- app/Livewire/Controllers/HttpConnectionHandler.php
- app/Providers/LivewireServiceProvider.php
- config/app.php
- tests/Feature/Http/Livewire/Navbar/DarkModeToggleTest.php
Livewire made a change a few months ago which introduced issues. It tries to generate a request based on the route/path of the livewire message, but if that page is a 404 (e.g. route does not exist), livewire throws an exception
> fix: 404 livewire error

- tests/Feature/Http/Livewire/WalletVoterTableTest.php
To emulate the issue (before applying the fix) add `'balance' => 1000 * 1e8,` in the model factory from the test
The test it fixed by applying the [same formatter](https://github.com/ArkEcosystem/laravel-foundation/blob/0add05766ae8f4671c6057f47c6f25d8d2588212/src/UserInterface/Components/Currency.php#L12) used on the component with the issue 
Closes https://app.clickup.com/t/863gue6g7
-   [ ] I added a short …
> fix: flaky wallet voter table test

- resources/views/blocks.blade.php
That attribute is used to hide a component while alpine (JS) is ready, was added 2 years ago and doesnt seem to be used, also is the reason the table doesnt show
Closes https://app.clickup.com/t/865cg28xp
> refactor: blocks page not loading 

- resources/views/app/blocks-by-wallet.blade.php
- resources/views/app/voters-by-wallet.blade.php
The Voters and Blocks tables for a wallet was hidden. A separate change seemed to have broken this as `x-cloak` wasn't being removed (usually gets removed by a parent alpine object)
> fix: hidden voters & blocks tables

- app/Http/Livewire/ExchangeTable.php
- app/Services/ExchangeRate.php
- app/Services/NumberFormatter.php
- resources/lang/en/tables.php
- resources/views/components/tables/desktop/exchanges.blade.php
- resources/views/components/tables/mobile/exchanges.blade.php
- tests/Unit/Services/ExchangeRateTest.php
- tests/Unit/Services/NumberFormatterTest.php
https://app.clickup.com/t/861mvv8xb
To test:
- Set env to production - `ARKSCAN_NETWORK=production` **make sure no other envs are set to look for devnet**
- Run horizon - `php artisan horizon`
- Load in Exchanges - `php artisan exchanges:load`
- Load in Exchange Details - `php artisan exchanges:fetch-details`
- Load in cache data - `php artisan explorer:cache-currencies-data`
- Go to exchanges page - `/exchanges` **should be visible from the navbar at this point**
- Change currency
-   [ ] I …
> refactor: exchanges use user currency

- resources/views/components/navbar/item.blade.php
small adjustment so entries without dropdown are in line with entries with dropdown
> fix: navbar dark text color single item entry

- resources/lang/en/pages.php
https://app.clickup.com/t/863h5cuw5
> fix: break words for address in download success toast

- app/Http/Livewire/Delegates/Delegates.php
- tests/Feature/Http/Livewire/Delegates/DelegatesTest.php
https://app.clickup.com/t/862kc1f00
> fix: delegates missed blocks with per page options

- resources/views/components/page-headers/generic.blade.php
was very dark before and hard to read
> fix: make page subtitle lighter to increase readability in dark mode

- app/Http/Livewire/Delegates/Delegates.php
- app/ViewModels/ForgingStatsViewModel.php
- resources/views/components/tables/desktop/delegates/missed-blocks.blade.php
- resources/views/components/tables/mobile/delegates/missed-blocks.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/delegates/number-of-voters.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/delegates/votes-percentage.blade.php
- resources/views/components/tables/rows/desktop/encapsulated/delegates/votes.blade.php
- tests/Analysis/AnalysisTest.php
- tests/Feature/Http/Livewire/Delegates/DelegatesTest.php
- tests/Feature/Http/Livewire/Delegates/MissedBlocksTest.php
- tests/Feature/Http/Livewire/Delegates/RecentVotesTest.php
- tests/Helpers.php
- tests/Unit/ViewModels/ForgingStatsViewModelTest.php
https://app.clickup.com/t/8678ur3qk
@ItsANameToo added some handling for when there are missed blocks for delegates that don't exist (e.g. when we run tests locally and it starts throwing an error). It effectively just hyphen's the data in the table. Sorting doesn't break under these circumstances either. If you'd prefer not to have this as it's only caused by local issues I can revert it
-   [ ] I added a short …
> refactor: delegates additional handling

- resources/views/components/navbar/mobile.blade.php
https://app.clickup.com/t/863h6be09
Will need testing on other devices and browsers. This specifically disables the navbar scroll lock for Safari browsers on iOS touchscreen devices
> refactor: disable scroll lock on ios safari

- app/Http/Livewire/Concerns/AvailablePeriods.php
https://app.clickup.com/t/862kf46m0
> fix: default to day for homepage statistics chart

- app/Services/Cache/Concerns/ManagesCache.php
- app/Services/Cache/MonitorCache.php
- app/Services/Cache/NetworkCache.php
https://app.clickup.com/t/862khmpj7
I've adjusted the caching so they all use the same (block time / 2). I'm not sure if this resolves the issue if I'm honest. The caches work as follows:
**Height**
Performs `Block::max('height')` so it relies on database
**Current Round**
Also uses `Block::max('height')` to determine how many blocks have been forged
**Next Slot**
Uses different logic based on the calculated slots for the whole round. 
-   [ ] I opened a corresponding card on Clickup for any …
> refactor: delegate monitor consistent cache ttl

- resources/views/components/tables/skeletons/encapsulated/mobile/delegates/monitor.blade.php
https://app.clickup.com/t/862khr6aw
> fix: delegate monitor mobile skeleton duplicate dropdown icon

- app/Http/Livewire/Delegates/Delegates.php
- tests/Feature/Http/Livewire/Delegates/DelegatesTest.php
https://app.clickup.com/t/862khv8xc
> fix: hide resigned delegates by default in table

- resources/lang/en/pages.php
- resources/views/livewire/home/statistics.blade.php
rename `volume` -> `exchange volume` on homepage
> chore: rename homepage statistics volume

- app/Services/ExchangeRate.php
- app/ViewModels/WalletViewModel.php
- tests/Feature/Http/Livewire/WalletBalanceTest.php
- tests/Unit/Services/ExchangeRateTest.php
https://app.clickup.com/t/86dqj70rk
> refactor: wallet balance use current currency rate

- resources/views/components/tables/desktop/top-accounts.blade.php
https://app.clickup.com/t/862kh72c8
the `flex` is needed to make sure the `leading` size gets applied properly, otherwise it changes to `20px` instead of `17px`
> fix: unalignment between table loading state and data top account

- app/Jobs/CacheProductivityByPublicKey.php
- app/ViewModels/Concerns/Wallet/CanForge.php
- tests/Unit/Console/Commands/CacheAnnualStatisticsTest.php
- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86dqnrgz7
instead of red -1% for new delegates, it will now show red 0% productivity
> refactor: don't use negative 1 for productivity

- app/Http/Controllers/BlocksController.php
As you [can see here](https://github.com/ArdentHQ/arkscan/blob/mainsail/app/Jobs/BuildForgingStats.php#L43-L59) he timestamp for the `forging_stats` is not stored as `ms` (is not multiplied by 1k) which means the condition that causes the exception is incorrect, we should not use the ms unix timestamp
Updating that condition should solve the out of range exceptions
-   [ ] I added a short description on how to test …
> fix: integer out of range exception

- app/Console/Commands/CacheDelegateAggregates.php
- app/Services/Cache/DelegateCache.php
- tests/Feature/Http/Controllers/ShowWalletControllerTest.php
- tests/Unit/Console/Commands/CacheDelegateAggregatesTest.php
- tests/Unit/ViewModels/WalletViewModelTest.php
https://app.clickup.com/t/86dt0wb60
This removes the TTL for the delegate aggregates cache data. The job itself was running minutely, but the data wasn't being updated for an hour because of how the TTL was being used. This made the job effectively redundant for 59 of the times it was run. I've changed it now so there is no expiry for the cache, but it always updates as and when the data is received. We could always have an expiry, though I don't see how useful it would be as the data will always be updated anyway (unless the cache key is changed).
-   [ ] I checked my (code) changes for …
> refactor: update delegate aggregates caching

- app/Console/Commands/CacheUsernames.php
- app/Services/Cache/Concerns/ManagesCache.php
- app/Services/Cache/WalletCache.php
- app/ViewModels/Concerns/Transaction/InteractsWithUsernames.php
- app/ViewModels/TransactionViewModel.php
- database/factories/WalletFactory.php
- resources/views/components/transaction/page/transaction-type.blade.php
- tests/Unit/Console/Commands/CacheUsernamesTest.php
https://app.clickup.com/t/86dt3eecx
To test:
- Register a username on a wallet
- Run `php artisan explorer:cache-usernames`
- Username should be shown in UI (wallet page, tx list, etc)
- Resign username
- Run `php artisan explorer:cache-usernames`
- Should no longer show username (apart from on the Username Registration transaction page)
- …
> refactor: username registration show name & resignation caching

- app/Services/MarketDataProviders/CoinGecko.php
https://app.clickup.com/t/86dt4cwyj
It seems coingecko have _potentially_ changed their API. The market chart endpoint has a max "days" of 365, which we didn't have a problem with previously. It gives this error currently:
>Your request exceeds the allowed time range. Public API users are limited to querying historical data within the past 365 days.
-   [ ] I added a short description on how to test this PR _(if …
> fix: pricing fetch from coingecko

- resources/js/wallet.js
https://app.clickup.com/t/86dtdxn2y
Can't test with mainsail yet so to test:
edit `resources/views/components/arkconnect/standby-delegate-toast.blade.php` like 3 to the below
```
show-property="true"
```
comment out `resources/js/wallet.js` like 141
This will show the standby toast message. It will briefly show no name or address as it's skipping some checks where it may not have fetched the voted delegate yet. In production it will show the popup after the voted delegate has been loaded
-   [ ] I …
> refactor: show address if no username

- app/Console/Commands/CacheAnnualStatistics.php
- tests/Unit/Console/Commands/CacheAnnualStatisticsTest.php
https://app.clickup.com/t/86dthqywa
The command now checks if there's data from the epoch year (e.g. 2017). If it is, it won't cache annual data automatically. This can be bypassed still with the `--all` flag.
> refactor: annual statistics command

- resources/views/components/tables/desktop/delegates/list-table.blade.php
https://app.clickup.com/t/86dtjd1n1
Don't really understand the root cause of this. The table row itself has a `wire:key` so it's not confusing it with other rows. I took it as an alpinejs oddity, and the issue seemed to disappear once I forced it to initiate some kind of alpine logic on the element that shows the voting indicator.
-   [ ] …
> fix: arkconnect delegate voting for indicator

- app/Services/Addresses/Aggregates/LatestWalletAggregate.php
- tests/Unit/Services/Addresses/Aggregates/LatestWalletAggregateTest.php
Related to https://app.clickup.com/t/86dtwxpzh
An observation I made where the wrong wallet is picked up as the latest. This is while running a local testnet, it would pick up the original sender as the newest and not the receiver
**note: I did enable `CORE_WALLET_SYNC_ENABLED` on my testnet prior to this change. I don't know if this enables storing cold wallets also, and whether the Explorer nodes have it enabled as well**
Edit: added additional tests to ensure everything works as expected
-   [ …
> refactor: statistics latest wallet ignore sender

- app/Http/Livewire/Validators/Validators.php
- app/ViewModels/Concerns/Wallet/HasVoters.php
https://app.clickup.com/t/86dv6bcbh
https://app.clickup.com/t/86dv6bd0c
> fix: validators & division by zero

- composer.lock
- resources/views/components/tables/rows/desktop/encapsulated/transaction-id.blade.php
https://app.clickup.com/t/86dv8cwjb
requires https://github.com/ArkEcosystem/laravel-foundation/pull/631
> refactor: update transaction id status styling

- composer.lock
- resources/lang/en/general.php
- resources/lang/en/pages.php
- resources/views/app/transaction.blade.php
- resources/views/components/transaction/page/status.blade.php
https://app.clickup.com/t/86dv84pvv
requires https://github.com/ArkEcosystem/laravel-foundation/pull/630
> refactor: transaction detail page add failed status

- .github/workflows/ci.yml
- .gitignore
Adds the `.phpunit.cache` folder to `.gitignore` to prevent a bunch of untracked files from appearing locally when running test:coverage. It also updates the GitHub Actions workflow to cache the .phpunit.cache directory, allowing us to benefit from faster subsequent test runs.
-   [ ] Tests _(if …
> chore: use phpunit cache on github actions

- app/Http/Livewire/Concerns/HasTableFilter.php
- resources/views/components/general/encapsulated/amount-fiat-tooltip.blade.php
- tests/Feature/Http/Livewire/Delegates/DelegatesTest.php
- tests/Feature/Http/Livewire/Delegates/RecentVotesTest.php
- tests/Feature/Http/Livewire/TransactionTableTest.php
- tests/Feature/Http/Livewire/WalletTransactionTableTest.php
https://app.clickup.com/t/86dvpr1py
Somewhere along the way, I believe in the move to v3 of Livewire, something happened whereby the `updated` hook gets triggered on history change (going forward/backwards in the browser). In this case, the change resulted in the `$filter` property always triggering the `update` hooks, even though the value doesn't change. The fix in this case is to do a specific check to see if anything changes and to reset the page if it has. I needed to switch to the `updating` hook in order to do this prior to the value being changed in the component as it's already changed at that point.
-   [ ] I checked my UI changes …
> fix: history pagination reset

- resources/views/components/tables/rows/desktop/encapsulated/address.blade.php
https://app.clickup.com/t/86dvnzz5u
Removes an extra line added here https://github.com/ArdentHQ/arkscan/pull/1142/files#diff-f945b1db2b2ea716748bced8e4fc92294d4c31dac0c6360f5c7c66da918f9668R36. Does not cause any issue because the slot overrides the value but still is an error.
-   [ ] Tests _(if …
> chore: remove extra parameter on address component

- app/ViewModels/Concerns/Transaction/CanBeValidatorRegistration.php
https://app.clickup.com/t/86dvfy8p0
This code is unreachable. If `rawPayload` is null, it will exit at the `isValidatorRegistration` call. The only way for `getMethodData` to return null is if `rawPayload` does.
Edit: my theory is that I added the null check to satisfy phpstan
-   [ ] Tests _(if …
> refactor: validator public key remove unused code

- resources/views/components/stats/insights/desktop/validator-row.blade.php
- resources/views/components/stats/insights/mobile/validator-row.blade.php
We have enough space to truncate with more characters, but it doesn’t seem like we’ve changed the default truncation length for addresses in the rest of the app, so I’m keeping the default one. Open to discussion.
https://app.clickup.com/t/86dvpfp0v
-   [ ] Ready to be …
> refactor: truncate validator stats addresses

- resources/views/components/arkconnect/modal/unsupported-browser.blade.php
- resources/views/components/navbar/arkconnect.blade.php
Errors occur when using the browser devtools and opening the page in mobile view with the extension previously installed. Since it is detected as mobile, the browser is considered unsupported so it shows the button the shows the "unsupported modal". However, since the the extension is already installed it also shows the button for that scenario.
An extra condition was added to hide the "unsupported" button if the extension is already installed.
Note: also adjusted the width of the button
https://app.clickup.com/t/86dvpz0gu
-   [ ] I checked my (code) changes for obvious issues, debug …
> fix: double button on mobile

- app/Console/Commands/CacheKnownWallets.php
- app/Services/Cache/Concerns/ManagesCache.php
- app/Services/Cache/WalletCache.php
- app/ViewModels/ForgingStatsViewModel.php
- resources/views/components/tables/desktop/validators/missed-blocks.blade.php
- resources/views/components/transaction/page/addressing.blade.php
- resources/views/components/transaction/page/section-detail/address.blade.php
- tests/Feature/Http/Livewire/Validators/RecentVotesTest.php
- tests/Unit/Console/Commands/CacheKnownWalletsTest.php
https://app.clickup.com/t/86dvbygg4
> refactor: username ui improvements

- resources/views/app/block.blade.php
- resources/views/components/block/page/detail-pagination.blade.php
- resources/views/components/block/page/transaction-list.blade.php
- resources/views/components/general/page-section/confirmations.blade.php
- resources/views/components/general/page-section/container.blade.php
https://app.clickup.com/t/86dvvnj05
This is for mainnet/devnet so you'll need database access for those
> feat: block detail pagination

- app/Models/Scopes/MultiPaymentTotalAmountScope.php
- app/Providers/EloquentServiceProvider.php
- app/Services/Transactions/Aggregates/Historical/AveragesAggregate.php
- database/factories/TransactionFactory.php
- tests/Feature/Http/Livewire/Stats/InsightsTest.php
- tests/Unit/Console/Commands/CacheTransactionsTest.php
- tests/Unit/Services/Transactions/Aggregates/Historical/AveragesAggregateTest.php
https://app.clickup.com/t/86dvdvux1
> refactor: averages aggregate include multipayment

- resources/views/livewire/home/statistics.blade.php
Currently it's not showing any decimals since the returned supply is a round number, but adding a `round` method to prevent issues in case that changes.
https://app.clickup.com/t/86dwc6gh0
> refactor: prevent decimals on supply

- resources/views/components/transaction/page/summary.blade.php
noticed while working on https://app.clickup.com/t/86dx2ga24
there's a scenario where validator resignations were incorrectly using the transaction model as a the amount argument which would never work. this changes it so that the amount is passed in directly. related to https://github.com/ArdentHQ/arkscan/pull/1216
resolves [app.clickup.com/t/86dx2qpq4](https://app.clickup.com/t/86dx2qpq4)
-   [ ] I added a short …
> fix: transaction amount component handling

- app/Console/Commands/CacheAnnualStatistics.php
- app/Services/Transactions/Aggregates/Historical/AveragesAggregate.php
- database/factories/TransactionFactory.php
- tests/Unit/Console/Commands/CacheAnnualStatisticsTest.php
https://app.clickup.com/t/86dvxzg6t
Added the MultipaymentTotalAmountScope to the CacheAnnualStatistics calculation. While doing this, I realised that it was also taking the `value` for multipayments and including that in the total, as well as the recipient amounts (did the same in the AveragesAggregate). So this fixes AveragesAggregate and adds multipay amounts to annual statistics
-   [ ] I added a short …
> refactor: annual statistics calculate multipayment

- app/Services/Transactions/Aggregates/LargestTransactionAggregate.php
https://app.clickup.com/t/86dvxzh7f
I think it's redundant to add specific scopes for the LargestTransactionAggregate so this just removed the TODO
> chore: remove largest transaction todo
